template: native
provider: provider-k0s
major-version: 0
providerDefaultBranch: main
publishRegistry: false
providerVersion: github.com/ydkn/pulumi-k0s/provider.Version
parallel: 3
sdkModuleDir: sdk/go/pulumi-k0s
# For some reason this is required. If it's omitted all of the env keys get duplicated.
envOverride:
  FOO: BAR
