version: 2

project_name: pulumi-k0s

builds:
  - id: pulumi-resource-k0s
    dir: provider
    main: ./cmd/pulumi-resource-k0s/
    binary: pulumi-resource-k0s
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/ydkn/pulumi-k0s/provider.Version={{.Tag}}

archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT"

changelog:
  disable: true

release:
  disable: false
