archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - make gen
builds:
  - binary: pulumi-resource-k0s
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/ydkn/pulumi-k0s/provider.Version={{ .Tag }}
    main: ./cmd/pulumi-resource-k0s/
changelog:
  skip: true
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
