// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s;

import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("k0s");
/**
 * Maximum number of hosts to configure in parallel, set to 0 for unlimited
 * 
 */
    public Optional<Integer> concurrency() {
        return Codegen.integerProp("concurrency").config(config).env("PULUMI_K0S_CONCURRENCY").def(30).get();
    }
/**
 * Maximum number of files to upload in parallel, set to 0 for unlimited
 * 
 */
    public Optional<Integer> concurrentUploads() {
        return Codegen.integerProp("concurrentUploads").config(config).env("PULUMI_K0S_CONCURRENT_UPLOADS").def(5).get();
    }
/**
 * Do not drain worker nodes when upgrading
 * 
 */
    public Optional<Boolean> noDrain() {
        return Codegen.booleanProp("noDrain").config(config).env("PULUMI_K0S_NO_DRAIN").def(false).get();
    }
/**
 * Do not wait for worker nodes to join
 * 
 */
    public Optional<Boolean> noWait() {
        return Codegen.booleanProp("noWait").config(config).env("PULUMI_K0S_NO_WAIT").def(false).get();
    }
/**
 * Skip downgrade check
 * 
 */
    public Optional<Boolean> skipDowngradeCheck() {
        return Codegen.booleanProp("skipDowngradeCheck").config(config).env("PULUMI_K0S_SKIP_DOWNGRADE_CHECK").def(false).get();
    }
}
