// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.ydkn.k0s.outputs.ClusterHost;
import com.ydkn.k0s.outputs.ClusterK0s;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClusterSpec {
    /**
     * @return The hosts that will form the cluster.
     * 
     */
    private List<ClusterHost> hosts;
    /**
     * @return K0s configuration.
     * 
     */
    private @Nullable ClusterK0s k0s;

    private ClusterSpec() {}
    /**
     * @return The hosts that will form the cluster.
     * 
     */
    public List<ClusterHost> hosts() {
        return this.hosts;
    }
    /**
     * @return K0s configuration.
     * 
     */
    public Optional<ClusterK0s> k0s() {
        return Optional.ofNullable(this.k0s);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterSpec defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<ClusterHost> hosts;
        private @Nullable ClusterK0s k0s;
        public Builder() {}
        public Builder(ClusterSpec defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.hosts = defaults.hosts;
    	      this.k0s = defaults.k0s;
        }

        @CustomType.Setter
        public Builder hosts(List<ClusterHost> hosts) {
            if (hosts == null) {
              throw new MissingRequiredPropertyException("ClusterSpec", "hosts");
            }
            this.hosts = hosts;
            return this;
        }
        public Builder hosts(ClusterHost... hosts) {
            return hosts(List.of(hosts));
        }
        @CustomType.Setter
        public Builder k0s(@Nullable ClusterK0s k0s) {

            this.k0s = k0s;
            return this;
        }
        public ClusterSpec build() {
            final var _resultValue = new ClusterSpec();
            _resultValue.hosts = hosts;
            _resultValue.k0s = k0s;
            return _resultValue;
        }
    }
}
