// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.ydkn.k0s.outputs.ClusterFile;
import com.ydkn.k0s.outputs.ClusterHooks;
import com.ydkn.k0s.outputs.ClusterLocalhost;
import com.ydkn.k0s.outputs.ClusterOpenSSH;
import com.ydkn.k0s.outputs.ClusterSSH;
import com.ydkn.k0s.outputs.ClusterWinRM;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClusterHost {
    private @Nullable Map<String,String> environment;
    private @Nullable List<ClusterFile> files;
    private @Nullable ClusterHooks hooks;
    private @Nullable String hostname;
    private @Nullable List<String> installFlags;
    private @Nullable String k0sBinaryPath;
    private @Nullable ClusterLocalhost localhost;
    private @Nullable Boolean noTaints;
    private @Nullable ClusterOpenSSH openSSH;
    private @Nullable String os;
    private @Nullable String privateAddress;
    private @Nullable String privateInterface;
    private String role;
    private @Nullable ClusterSSH ssh;
    private @Nullable Boolean uploadBinary;
    private @Nullable ClusterWinRM winRM;

    private ClusterHost() {}
    public Map<String,String> environment() {
        return this.environment == null ? Map.of() : this.environment;
    }
    public List<ClusterFile> files() {
        return this.files == null ? List.of() : this.files;
    }
    public Optional<ClusterHooks> hooks() {
        return Optional.ofNullable(this.hooks);
    }
    public Optional<String> hostname() {
        return Optional.ofNullable(this.hostname);
    }
    public List<String> installFlags() {
        return this.installFlags == null ? List.of() : this.installFlags;
    }
    public Optional<String> k0sBinaryPath() {
        return Optional.ofNullable(this.k0sBinaryPath);
    }
    public Optional<ClusterLocalhost> localhost() {
        return Optional.ofNullable(this.localhost);
    }
    public Optional<Boolean> noTaints() {
        return Optional.ofNullable(this.noTaints);
    }
    public Optional<ClusterOpenSSH> openSSH() {
        return Optional.ofNullable(this.openSSH);
    }
    public Optional<String> os() {
        return Optional.ofNullable(this.os);
    }
    public Optional<String> privateAddress() {
        return Optional.ofNullable(this.privateAddress);
    }
    public Optional<String> privateInterface() {
        return Optional.ofNullable(this.privateInterface);
    }
    public String role() {
        return this.role;
    }
    public Optional<ClusterSSH> ssh() {
        return Optional.ofNullable(this.ssh);
    }
    public Optional<Boolean> uploadBinary() {
        return Optional.ofNullable(this.uploadBinary);
    }
    public Optional<ClusterWinRM> winRM() {
        return Optional.ofNullable(this.winRM);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterHost defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Map<String,String> environment;
        private @Nullable List<ClusterFile> files;
        private @Nullable ClusterHooks hooks;
        private @Nullable String hostname;
        private @Nullable List<String> installFlags;
        private @Nullable String k0sBinaryPath;
        private @Nullable ClusterLocalhost localhost;
        private @Nullable Boolean noTaints;
        private @Nullable ClusterOpenSSH openSSH;
        private @Nullable String os;
        private @Nullable String privateAddress;
        private @Nullable String privateInterface;
        private String role;
        private @Nullable ClusterSSH ssh;
        private @Nullable Boolean uploadBinary;
        private @Nullable ClusterWinRM winRM;
        public Builder() {}
        public Builder(ClusterHost defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.environment = defaults.environment;
    	      this.files = defaults.files;
    	      this.hooks = defaults.hooks;
    	      this.hostname = defaults.hostname;
    	      this.installFlags = defaults.installFlags;
    	      this.k0sBinaryPath = defaults.k0sBinaryPath;
    	      this.localhost = defaults.localhost;
    	      this.noTaints = defaults.noTaints;
    	      this.openSSH = defaults.openSSH;
    	      this.os = defaults.os;
    	      this.privateAddress = defaults.privateAddress;
    	      this.privateInterface = defaults.privateInterface;
    	      this.role = defaults.role;
    	      this.ssh = defaults.ssh;
    	      this.uploadBinary = defaults.uploadBinary;
    	      this.winRM = defaults.winRM;
        }

        @CustomType.Setter
        public Builder environment(@Nullable Map<String,String> environment) {

            this.environment = environment;
            return this;
        }
        @CustomType.Setter
        public Builder files(@Nullable List<ClusterFile> files) {

            this.files = files;
            return this;
        }
        public Builder files(ClusterFile... files) {
            return files(List.of(files));
        }
        @CustomType.Setter
        public Builder hooks(@Nullable ClusterHooks hooks) {

            this.hooks = hooks;
            return this;
        }
        @CustomType.Setter
        public Builder hostname(@Nullable String hostname) {

            this.hostname = hostname;
            return this;
        }
        @CustomType.Setter
        public Builder installFlags(@Nullable List<String> installFlags) {

            this.installFlags = installFlags;
            return this;
        }
        public Builder installFlags(String... installFlags) {
            return installFlags(List.of(installFlags));
        }
        @CustomType.Setter
        public Builder k0sBinaryPath(@Nullable String k0sBinaryPath) {

            this.k0sBinaryPath = k0sBinaryPath;
            return this;
        }
        @CustomType.Setter
        public Builder localhost(@Nullable ClusterLocalhost localhost) {

            this.localhost = localhost;
            return this;
        }
        @CustomType.Setter
        public Builder noTaints(@Nullable Boolean noTaints) {

            this.noTaints = noTaints;
            return this;
        }
        @CustomType.Setter
        public Builder openSSH(@Nullable ClusterOpenSSH openSSH) {

            this.openSSH = openSSH;
            return this;
        }
        @CustomType.Setter
        public Builder os(@Nullable String os) {

            this.os = os;
            return this;
        }
        @CustomType.Setter
        public Builder privateAddress(@Nullable String privateAddress) {

            this.privateAddress = privateAddress;
            return this;
        }
        @CustomType.Setter
        public Builder privateInterface(@Nullable String privateInterface) {

            this.privateInterface = privateInterface;
            return this;
        }
        @CustomType.Setter
        public Builder role(String role) {
            if (role == null) {
              throw new MissingRequiredPropertyException("ClusterHost", "role");
            }
            this.role = role;
            return this;
        }
        @CustomType.Setter
        public Builder ssh(@Nullable ClusterSSH ssh) {

            this.ssh = ssh;
            return this;
        }
        @CustomType.Setter
        public Builder uploadBinary(@Nullable Boolean uploadBinary) {

            this.uploadBinary = uploadBinary;
            return this;
        }
        @CustomType.Setter
        public Builder winRM(@Nullable ClusterWinRM winRM) {

            this.winRM = winRM;
            return this;
        }
        public ClusterHost build() {
            final var _resultValue = new ClusterHost();
            _resultValue.environment = environment;
            _resultValue.files = files;
            _resultValue.hooks = hooks;
            _resultValue.hostname = hostname;
            _resultValue.installFlags = installFlags;
            _resultValue.k0sBinaryPath = k0sBinaryPath;
            _resultValue.localhost = localhost;
            _resultValue.noTaints = noTaints;
            _resultValue.openSSH = openSSH;
            _resultValue.os = os;
            _resultValue.privateAddress = privateAddress;
            _resultValue.privateInterface = privateInterface;
            _resultValue.role = role;
            _resultValue.ssh = ssh;
            _resultValue.uploadBinary = uploadBinary;
            _resultValue.winRM = winRM;
            return _resultValue;
        }
    }
}
