// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import com.ydkn.k0s.outputs.K0s;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClusterK0s {
    /**
     * @return K0s configuration.
     * 
     */
    private @Nullable K0s config;
    /**
     * @return Whether to use dynamic configuration.
     * 
     */
    private @Nullable Boolean dynamicConfig;
    /**
     * @return The hosts that will form the cluster.
     * 
     */
    private @Nullable String version;
    /**
     * @return The k0s version channel to use.
     * 
     */
    private @Nullable String versionChannel;

    private ClusterK0s() {}
    /**
     * @return K0s configuration.
     * 
     */
    public Optional<K0s> config() {
        return Optional.ofNullable(this.config);
    }
    /**
     * @return Whether to use dynamic configuration.
     * 
     */
    public Optional<Boolean> dynamicConfig() {
        return Optional.ofNullable(this.dynamicConfig);
    }
    /**
     * @return The hosts that will form the cluster.
     * 
     */
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }
    /**
     * @return The k0s version channel to use.
     * 
     */
    public Optional<String> versionChannel() {
        return Optional.ofNullable(this.versionChannel);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterK0s defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable K0s config;
        private @Nullable Boolean dynamicConfig;
        private @Nullable String version;
        private @Nullable String versionChannel;
        public Builder() {}
        public Builder(ClusterK0s defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.config = defaults.config;
    	      this.dynamicConfig = defaults.dynamicConfig;
    	      this.version = defaults.version;
    	      this.versionChannel = defaults.versionChannel;
        }

        @CustomType.Setter
        public Builder config(@Nullable K0s config) {

            this.config = config;
            return this;
        }
        @CustomType.Setter
        public Builder dynamicConfig(@Nullable Boolean dynamicConfig) {

            this.dynamicConfig = dynamicConfig;
            return this;
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        @CustomType.Setter
        public Builder versionChannel(@Nullable String versionChannel) {

            this.versionChannel = versionChannel;
            return this;
        }
        public ClusterK0s build() {
            final var _resultValue = new ClusterK0s();
            _resultValue.config = config;
            _resultValue.dynamicConfig = dynamicConfig;
            _resultValue.version = version;
            _resultValue.versionChannel = versionChannel;
            return _resultValue;
        }
    }
}
