// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import com.ydkn.k0s.outputs.K0sMetadata;
import com.ydkn.k0s.outputs.K0sSpec;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class K0s {
    /**
     * @return The API version of the k0s configuration.
     * 
     */
    private @Nullable String apiVersion;
    /**
     * @return The kind of the k0s configuration.
     * 
     */
    private @Nullable String kind;
    /**
     * @return K0s configuration metadata.
     * 
     */
    private @Nullable K0sMetadata metadata;
    /**
     * @return K0s configuration specification.
     * 
     */
    private @Nullable K0sSpec spec;

    private K0s() {}
    /**
     * @return The API version of the k0s configuration.
     * 
     */
    public Optional<String> apiVersion() {
        return Optional.ofNullable(this.apiVersion);
    }
    /**
     * @return The kind of the k0s configuration.
     * 
     */
    public Optional<String> kind() {
        return Optional.ofNullable(this.kind);
    }
    /**
     * @return K0s configuration metadata.
     * 
     */
    public Optional<K0sMetadata> metadata() {
        return Optional.ofNullable(this.metadata);
    }
    /**
     * @return K0s configuration specification.
     * 
     */
    public Optional<K0sSpec> spec() {
        return Optional.ofNullable(this.spec);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0s defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String apiVersion;
        private @Nullable String kind;
        private @Nullable K0sMetadata metadata;
        private @Nullable K0sSpec spec;
        public Builder() {}
        public Builder(K0s defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.apiVersion = defaults.apiVersion;
    	      this.kind = defaults.kind;
    	      this.metadata = defaults.metadata;
    	      this.spec = defaults.spec;
        }

        @CustomType.Setter
        public Builder apiVersion(@Nullable String apiVersion) {

            this.apiVersion = apiVersion;
            return this;
        }
        @CustomType.Setter
        public Builder kind(@Nullable String kind) {

            this.kind = kind;
            return this;
        }
        @CustomType.Setter
        public Builder metadata(@Nullable K0sMetadata metadata) {

            this.metadata = metadata;
            return this;
        }
        @CustomType.Setter
        public Builder spec(@Nullable K0sSpec spec) {

            this.spec = spec;
            return this;
        }
        public K0s build() {
            final var _resultValue = new K0s();
            _resultValue.apiVersion = apiVersion;
            _resultValue.kind = kind;
            _resultValue.metadata = metadata;
            _resultValue.spec = spec;
            return _resultValue;
        }
    }
}
