// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class K0sAPI {
    private @Nullable String address;
    private @Nullable String externalAddress;
    private @Nullable Map<String,String> extraArgs;
    /**
     * @return The port the k0s API will listen on.
     * 
     */
    private @Nullable Integer k0sApiPort;
    /**
     * @return The port the Kubernetes API will listen on.
     * 
     */
    private @Nullable Integer port;
    private @Nullable List<String> sans;

    private K0sAPI() {}
    public Optional<String> address() {
        return Optional.ofNullable(this.address);
    }
    public Optional<String> externalAddress() {
        return Optional.ofNullable(this.externalAddress);
    }
    public Map<String,String> extraArgs() {
        return this.extraArgs == null ? Map.of() : this.extraArgs;
    }
    /**
     * @return The port the k0s API will listen on.
     * 
     */
    public Optional<Integer> k0sApiPort() {
        return Optional.ofNullable(this.k0sApiPort);
    }
    /**
     * @return The port the Kubernetes API will listen on.
     * 
     */
    public Optional<Integer> port() {
        return Optional.ofNullable(this.port);
    }
    public List<String> sans() {
        return this.sans == null ? List.of() : this.sans;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0sAPI defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String address;
        private @Nullable String externalAddress;
        private @Nullable Map<String,String> extraArgs;
        private @Nullable Integer k0sApiPort;
        private @Nullable Integer port;
        private @Nullable List<String> sans;
        public Builder() {}
        public Builder(K0sAPI defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.address = defaults.address;
    	      this.externalAddress = defaults.externalAddress;
    	      this.extraArgs = defaults.extraArgs;
    	      this.k0sApiPort = defaults.k0sApiPort;
    	      this.port = defaults.port;
    	      this.sans = defaults.sans;
        }

        @CustomType.Setter
        public Builder address(@Nullable String address) {

            this.address = address;
            return this;
        }
        @CustomType.Setter
        public Builder externalAddress(@Nullable String externalAddress) {

            this.externalAddress = externalAddress;
            return this;
        }
        @CustomType.Setter
        public Builder extraArgs(@Nullable Map<String,String> extraArgs) {

            this.extraArgs = extraArgs;
            return this;
        }
        @CustomType.Setter
        public Builder k0sApiPort(@Nullable Integer k0sApiPort) {

            this.k0sApiPort = k0sApiPort;
            return this;
        }
        @CustomType.Setter
        public Builder port(@Nullable Integer port) {

            this.port = port;
            return this;
        }
        @CustomType.Setter
        public Builder sans(@Nullable List<String> sans) {

            this.sans = sans;
            return this;
        }
        public Builder sans(String... sans) {
            return sans(List.of(sans));
        }
        public K0sAPI build() {
            final var _resultValue = new K0sAPI();
            _resultValue.address = address;
            _resultValue.externalAddress = externalAddress;
            _resultValue.extraArgs = extraArgs;
            _resultValue.k0sApiPort = k0sApiPort;
            _resultValue.port = port;
            _resultValue.sans = sans;
            return _resultValue;
        }
    }
}
