// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class K0sControllerManager {
    private @Nullable Map<String,String> extraArgs;

    private K0sControllerManager() {}
    public Map<String,String> extraArgs() {
        return this.extraArgs == null ? Map.of() : this.extraArgs;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0sControllerManager defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Map<String,String> extraArgs;
        public Builder() {}
        public Builder(K0sControllerManager defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.extraArgs = defaults.extraArgs;
        }

        @CustomType.Setter
        public Builder extraArgs(@Nullable Map<String,String> extraArgs) {

            this.extraArgs = extraArgs;
            return this;
        }
        public K0sControllerManager build() {
            final var _resultValue = new K0sControllerManager();
            _resultValue.extraArgs = extraArgs;
            return _resultValue;
        }
    }
}
