// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import com.ydkn.k0s.outputs.K0sImage;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class K0sCalicoImage {
    private @Nullable K0sImage cni;
    private @Nullable K0sImage flexvolume;
    private @Nullable K0sImage kubecontrollers;
    private @Nullable K0sImage node;

    private K0sCalicoImage() {}
    public Optional<K0sImage> cni() {
        return Optional.ofNullable(this.cni);
    }
    public Optional<K0sImage> flexvolume() {
        return Optional.ofNullable(this.flexvolume);
    }
    public Optional<K0sImage> kubecontrollers() {
        return Optional.ofNullable(this.kubecontrollers);
    }
    public Optional<K0sImage> node() {
        return Optional.ofNullable(this.node);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0sCalicoImage defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable K0sImage cni;
        private @Nullable K0sImage flexvolume;
        private @Nullable K0sImage kubecontrollers;
        private @Nullable K0sImage node;
        public Builder() {}
        public Builder(K0sCalicoImage defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cni = defaults.cni;
    	      this.flexvolume = defaults.flexvolume;
    	      this.kubecontrollers = defaults.kubecontrollers;
    	      this.node = defaults.node;
        }

        @CustomType.Setter
        public Builder cni(@Nullable K0sImage cni) {

            this.cni = cni;
            return this;
        }
        @CustomType.Setter
        public Builder flexvolume(@Nullable K0sImage flexvolume) {

            this.flexvolume = flexvolume;
            return this;
        }
        @CustomType.Setter
        public Builder kubecontrollers(@Nullable K0sImage kubecontrollers) {

            this.kubecontrollers = kubecontrollers;
            return this;
        }
        @CustomType.Setter
        public Builder node(@Nullable K0sImage node) {

            this.node = node;
            return this;
        }
        public K0sCalicoImage build() {
            final var _resultValue = new K0sCalicoImage();
            _resultValue.cni = cni;
            _resultValue.flexvolume = flexvolume;
            _resultValue.kubecontrollers = kubecontrollers;
            _resultValue.node = node;
            return _resultValue;
        }
    }
}
