// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class K0sCalico {
    private @Nullable Map<String,String> envVars;
    private @Nullable String flexVolumeDriverPath;
    private @Nullable String ipAutodetectionMethod;
    private @Nullable String mode;
    private @Nullable Integer mtu;
    private @Nullable String overlay;
    private @Nullable Integer vxlanPort;
    private @Nullable Integer vxlanVNI;
    private @Nullable Boolean wireguard;

    private K0sCalico() {}
    public Map<String,String> envVars() {
        return this.envVars == null ? Map.of() : this.envVars;
    }
    public Optional<String> flexVolumeDriverPath() {
        return Optional.ofNullable(this.flexVolumeDriverPath);
    }
    public Optional<String> ipAutodetectionMethod() {
        return Optional.ofNullable(this.ipAutodetectionMethod);
    }
    public Optional<String> mode() {
        return Optional.ofNullable(this.mode);
    }
    public Optional<Integer> mtu() {
        return Optional.ofNullable(this.mtu);
    }
    public Optional<String> overlay() {
        return Optional.ofNullable(this.overlay);
    }
    public Optional<Integer> vxlanPort() {
        return Optional.ofNullable(this.vxlanPort);
    }
    public Optional<Integer> vxlanVNI() {
        return Optional.ofNullable(this.vxlanVNI);
    }
    public Optional<Boolean> wireguard() {
        return Optional.ofNullable(this.wireguard);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0sCalico defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Map<String,String> envVars;
        private @Nullable String flexVolumeDriverPath;
        private @Nullable String ipAutodetectionMethod;
        private @Nullable String mode;
        private @Nullable Integer mtu;
        private @Nullable String overlay;
        private @Nullable Integer vxlanPort;
        private @Nullable Integer vxlanVNI;
        private @Nullable Boolean wireguard;
        public Builder() {}
        public Builder(K0sCalico defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.envVars = defaults.envVars;
    	      this.flexVolumeDriverPath = defaults.flexVolumeDriverPath;
    	      this.ipAutodetectionMethod = defaults.ipAutodetectionMethod;
    	      this.mode = defaults.mode;
    	      this.mtu = defaults.mtu;
    	      this.overlay = defaults.overlay;
    	      this.vxlanPort = defaults.vxlanPort;
    	      this.vxlanVNI = defaults.vxlanVNI;
    	      this.wireguard = defaults.wireguard;
        }

        @CustomType.Setter
        public Builder envVars(@Nullable Map<String,String> envVars) {

            this.envVars = envVars;
            return this;
        }
        @CustomType.Setter
        public Builder flexVolumeDriverPath(@Nullable String flexVolumeDriverPath) {

            this.flexVolumeDriverPath = flexVolumeDriverPath;
            return this;
        }
        @CustomType.Setter
        public Builder ipAutodetectionMethod(@Nullable String ipAutodetectionMethod) {

            this.ipAutodetectionMethod = ipAutodetectionMethod;
            return this;
        }
        @CustomType.Setter
        public Builder mode(@Nullable String mode) {

            this.mode = mode;
            return this;
        }
        @CustomType.Setter
        public Builder mtu(@Nullable Integer mtu) {

            this.mtu = mtu;
            return this;
        }
        @CustomType.Setter
        public Builder overlay(@Nullable String overlay) {

            this.overlay = overlay;
            return this;
        }
        @CustomType.Setter
        public Builder vxlanPort(@Nullable Integer vxlanPort) {

            this.vxlanPort = vxlanPort;
            return this;
        }
        @CustomType.Setter
        public Builder vxlanVNI(@Nullable Integer vxlanVNI) {

            this.vxlanVNI = vxlanVNI;
            return this;
        }
        @CustomType.Setter
        public Builder wireguard(@Nullable Boolean wireguard) {

            this.wireguard = wireguard;
            return this;
        }
        public K0sCalico build() {
            final var _resultValue = new K0sCalico();
            _resultValue.envVars = envVars;
            _resultValue.flexVolumeDriverPath = flexVolumeDriverPath;
            _resultValue.ipAutodetectionMethod = ipAutodetectionMethod;
            _resultValue.mode = mode;
            _resultValue.mtu = mtu;
            _resultValue.overlay = overlay;
            _resultValue.vxlanPort = vxlanPort;
            _resultValue.vxlanVNI = vxlanVNI;
            _resultValue.wireguard = wireguard;
            return _resultValue;
        }
    }
}
