// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class K0sImage {
    private @Nullable String image;
    private @Nullable String version;

    private K0sImage() {}
    public Optional<String> image() {
        return Optional.ofNullable(this.image);
    }
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0sImage defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String image;
        private @Nullable String version;
        public Builder() {}
        public Builder(K0sImage defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.image = defaults.image;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder image(@Nullable String image) {

            this.image = image;
            return this;
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public K0sImage build() {
            final var _resultValue = new K0sImage();
            _resultValue.image = image;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
