// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class K0sInstallConfigUser {
    /**
     * @return The user the etcd process will run as.
     * 
     */
    private @Nullable String etcdUser;
    /**
     * @return The user the kine process will run as.
     * 
     */
    private @Nullable String kineUser;
    /**
     * @return The user the konnectivity process will run as.
     * 
     */
    private @Nullable String konnectivityUser;
    /**
     * @return The user the kube-apiserver process will run as.
     * 
     */
    private @Nullable String kubeAPIserverUser;
    /**
     * @return The user the kube-scheduler process will run as.
     * 
     */
    private @Nullable String kubeSchedulerUser;

    private K0sInstallConfigUser() {}
    /**
     * @return The user the etcd process will run as.
     * 
     */
    public Optional<String> etcdUser() {
        return Optional.ofNullable(this.etcdUser);
    }
    /**
     * @return The user the kine process will run as.
     * 
     */
    public Optional<String> kineUser() {
        return Optional.ofNullable(this.kineUser);
    }
    /**
     * @return The user the konnectivity process will run as.
     * 
     */
    public Optional<String> konnectivityUser() {
        return Optional.ofNullable(this.konnectivityUser);
    }
    /**
     * @return The user the kube-apiserver process will run as.
     * 
     */
    public Optional<String> kubeAPIserverUser() {
        return Optional.ofNullable(this.kubeAPIserverUser);
    }
    /**
     * @return The user the kube-scheduler process will run as.
     * 
     */
    public Optional<String> kubeSchedulerUser() {
        return Optional.ofNullable(this.kubeSchedulerUser);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0sInstallConfigUser defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String etcdUser;
        private @Nullable String kineUser;
        private @Nullable String konnectivityUser;
        private @Nullable String kubeAPIserverUser;
        private @Nullable String kubeSchedulerUser;
        public Builder() {}
        public Builder(K0sInstallConfigUser defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.etcdUser = defaults.etcdUser;
    	      this.kineUser = defaults.kineUser;
    	      this.konnectivityUser = defaults.konnectivityUser;
    	      this.kubeAPIserverUser = defaults.kubeAPIserverUser;
    	      this.kubeSchedulerUser = defaults.kubeSchedulerUser;
        }

        @CustomType.Setter
        public Builder etcdUser(@Nullable String etcdUser) {

            this.etcdUser = etcdUser;
            return this;
        }
        @CustomType.Setter
        public Builder kineUser(@Nullable String kineUser) {

            this.kineUser = kineUser;
            return this;
        }
        @CustomType.Setter
        public Builder konnectivityUser(@Nullable String konnectivityUser) {

            this.konnectivityUser = konnectivityUser;
            return this;
        }
        @CustomType.Setter
        public Builder kubeAPIserverUser(@Nullable String kubeAPIserverUser) {

            this.kubeAPIserverUser = kubeAPIserverUser;
            return this;
        }
        @CustomType.Setter
        public Builder kubeSchedulerUser(@Nullable String kubeSchedulerUser) {

            this.kubeSchedulerUser = kubeSchedulerUser;
            return this;
        }
        public K0sInstallConfigUser build() {
            final var _resultValue = new K0sInstallConfigUser();
            _resultValue.etcdUser = etcdUser;
            _resultValue.kineUser = kineUser;
            _resultValue.konnectivityUser = konnectivityUser;
            _resultValue.kubeAPIserverUser = kubeAPIserverUser;
            _resultValue.kubeSchedulerUser = kubeSchedulerUser;
            return _resultValue;
        }
    }
}
