// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class K0sKonnectivity {
    /**
     * @return The port the konnectivity admin server will listen on.
     * 
     */
    private @Nullable Integer adminPort;
    /**
     * @return The port the konnectivity agent will listen on.
     * 
     */
    private @Nullable Integer agentPort;

    private K0sKonnectivity() {}
    /**
     * @return The port the konnectivity admin server will listen on.
     * 
     */
    public Optional<Integer> adminPort() {
        return Optional.ofNullable(this.adminPort);
    }
    /**
     * @return The port the konnectivity agent will listen on.
     * 
     */
    public Optional<Integer> agentPort() {
        return Optional.ofNullable(this.agentPort);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0sKonnectivity defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer adminPort;
        private @Nullable Integer agentPort;
        public Builder() {}
        public Builder(K0sKonnectivity defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.adminPort = defaults.adminPort;
    	      this.agentPort = defaults.agentPort;
        }

        @CustomType.Setter
        public Builder adminPort(@Nullable Integer adminPort) {

            this.adminPort = adminPort;
            return this;
        }
        @CustomType.Setter
        public Builder agentPort(@Nullable Integer agentPort) {

            this.agentPort = agentPort;
            return this;
        }
        public K0sKonnectivity build() {
            final var _resultValue = new K0sKonnectivity();
            _resultValue.adminPort = adminPort;
            _resultValue.agentPort = agentPort;
            return _resultValue;
        }
    }
}
