// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import com.ydkn.k0s.outputs.K0sKubeProxyIPTables;
import com.ydkn.k0s.outputs.K0sKubeProxyIPVS;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class K0sKubeProxy {
    /**
     * @return Disable kube-proxy.
     * 
     */
    private @Nullable Boolean disabled;
    private @Nullable K0sKubeProxyIPTables iptables;
    private @Nullable K0sKubeProxyIPVS ipvs;
    /**
     * @return The kube-proxy mode to use. One of &#39;iptables&#39; or &#39;ipvs&#39;.
     * 
     */
    private @Nullable String mode;
    private @Nullable String nodePortAddresses;

    private K0sKubeProxy() {}
    /**
     * @return Disable kube-proxy.
     * 
     */
    public Optional<Boolean> disabled() {
        return Optional.ofNullable(this.disabled);
    }
    public Optional<K0sKubeProxyIPTables> iptables() {
        return Optional.ofNullable(this.iptables);
    }
    public Optional<K0sKubeProxyIPVS> ipvs() {
        return Optional.ofNullable(this.ipvs);
    }
    /**
     * @return The kube-proxy mode to use. One of &#39;iptables&#39; or &#39;ipvs&#39;.
     * 
     */
    public Optional<String> mode() {
        return Optional.ofNullable(this.mode);
    }
    public Optional<String> nodePortAddresses() {
        return Optional.ofNullable(this.nodePortAddresses);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0sKubeProxy defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean disabled;
        private @Nullable K0sKubeProxyIPTables iptables;
        private @Nullable K0sKubeProxyIPVS ipvs;
        private @Nullable String mode;
        private @Nullable String nodePortAddresses;
        public Builder() {}
        public Builder(K0sKubeProxy defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.disabled = defaults.disabled;
    	      this.iptables = defaults.iptables;
    	      this.ipvs = defaults.ipvs;
    	      this.mode = defaults.mode;
    	      this.nodePortAddresses = defaults.nodePortAddresses;
        }

        @CustomType.Setter
        public Builder disabled(@Nullable Boolean disabled) {

            this.disabled = disabled;
            return this;
        }
        @CustomType.Setter
        public Builder iptables(@Nullable K0sKubeProxyIPTables iptables) {

            this.iptables = iptables;
            return this;
        }
        @CustomType.Setter
        public Builder ipvs(@Nullable K0sKubeProxyIPVS ipvs) {

            this.ipvs = ipvs;
            return this;
        }
        @CustomType.Setter
        public Builder mode(@Nullable String mode) {

            this.mode = mode;
            return this;
        }
        @CustomType.Setter
        public Builder nodePortAddresses(@Nullable String nodePortAddresses) {

            this.nodePortAddresses = nodePortAddresses;
            return this;
        }
        public K0sKubeProxy build() {
            final var _resultValue = new K0sKubeProxy();
            _resultValue.disabled = disabled;
            _resultValue.iptables = iptables;
            _resultValue.ipvs = ipvs;
            _resultValue.mode = mode;
            _resultValue.nodePortAddresses = nodePortAddresses;
            return _resultValue;
        }
    }
}
