// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import com.ydkn.k0s.outputs.K0sCalico;
import com.ydkn.k0s.outputs.K0sDualStack;
import com.ydkn.k0s.outputs.K0sKubeProxy;
import com.ydkn.k0s.outputs.K0sKubeRouter;
import com.ydkn.k0s.outputs.K0sNodeLocalLoadBalancing;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class K0sNetwork {
    /**
     * @return K0s calico configuration.
     * 
     */
    private @Nullable K0sCalico calico;
    private @Nullable String clusterDomain;
    /**
     * @return K0s dual-stack configuration.
     * 
     */
    private @Nullable K0sDualStack dualStack;
    /**
     * @return K0s kube-proxy configuration.
     * 
     */
    private @Nullable K0sKubeProxy kubeProxy;
    /**
     * @return K0s kube-router configuration.
     * 
     */
    private @Nullable K0sKubeRouter kuberouter;
    /**
     * @return K0s node local load balancing configuration.
     * 
     */
    private @Nullable K0sNodeLocalLoadBalancing nodeLocalLoadBalancing;
    /**
     * @return The CIDR from which Pod IPs are allocated.
     * 
     */
    private @Nullable String podCIDR;
    /**
     * @return The network provider to use.
     * 
     */
    private @Nullable String provider;
    /**
     * @return The CIDR from which Service IPs are allocated.
     * 
     */
    private @Nullable String serviceCIDR;

    private K0sNetwork() {}
    /**
     * @return K0s calico configuration.
     * 
     */
    public Optional<K0sCalico> calico() {
        return Optional.ofNullable(this.calico);
    }
    public Optional<String> clusterDomain() {
        return Optional.ofNullable(this.clusterDomain);
    }
    /**
     * @return K0s dual-stack configuration.
     * 
     */
    public Optional<K0sDualStack> dualStack() {
        return Optional.ofNullable(this.dualStack);
    }
    /**
     * @return K0s kube-proxy configuration.
     * 
     */
    public Optional<K0sKubeProxy> kubeProxy() {
        return Optional.ofNullable(this.kubeProxy);
    }
    /**
     * @return K0s kube-router configuration.
     * 
     */
    public Optional<K0sKubeRouter> kuberouter() {
        return Optional.ofNullable(this.kuberouter);
    }
    /**
     * @return K0s node local load balancing configuration.
     * 
     */
    public Optional<K0sNodeLocalLoadBalancing> nodeLocalLoadBalancing() {
        return Optional.ofNullable(this.nodeLocalLoadBalancing);
    }
    /**
     * @return The CIDR from which Pod IPs are allocated.
     * 
     */
    public Optional<String> podCIDR() {
        return Optional.ofNullable(this.podCIDR);
    }
    /**
     * @return The network provider to use.
     * 
     */
    public Optional<String> provider() {
        return Optional.ofNullable(this.provider);
    }
    /**
     * @return The CIDR from which Service IPs are allocated.
     * 
     */
    public Optional<String> serviceCIDR() {
        return Optional.ofNullable(this.serviceCIDR);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0sNetwork defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable K0sCalico calico;
        private @Nullable String clusterDomain;
        private @Nullable K0sDualStack dualStack;
        private @Nullable K0sKubeProxy kubeProxy;
        private @Nullable K0sKubeRouter kuberouter;
        private @Nullable K0sNodeLocalLoadBalancing nodeLocalLoadBalancing;
        private @Nullable String podCIDR;
        private @Nullable String provider;
        private @Nullable String serviceCIDR;
        public Builder() {}
        public Builder(K0sNetwork defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.calico = defaults.calico;
    	      this.clusterDomain = defaults.clusterDomain;
    	      this.dualStack = defaults.dualStack;
    	      this.kubeProxy = defaults.kubeProxy;
    	      this.kuberouter = defaults.kuberouter;
    	      this.nodeLocalLoadBalancing = defaults.nodeLocalLoadBalancing;
    	      this.podCIDR = defaults.podCIDR;
    	      this.provider = defaults.provider;
    	      this.serviceCIDR = defaults.serviceCIDR;
        }

        @CustomType.Setter
        public Builder calico(@Nullable K0sCalico calico) {

            this.calico = calico;
            return this;
        }
        @CustomType.Setter
        public Builder clusterDomain(@Nullable String clusterDomain) {

            this.clusterDomain = clusterDomain;
            return this;
        }
        @CustomType.Setter
        public Builder dualStack(@Nullable K0sDualStack dualStack) {

            this.dualStack = dualStack;
            return this;
        }
        @CustomType.Setter
        public Builder kubeProxy(@Nullable K0sKubeProxy kubeProxy) {

            this.kubeProxy = kubeProxy;
            return this;
        }
        @CustomType.Setter
        public Builder kuberouter(@Nullable K0sKubeRouter kuberouter) {

            this.kuberouter = kuberouter;
            return this;
        }
        @CustomType.Setter
        public Builder nodeLocalLoadBalancing(@Nullable K0sNodeLocalLoadBalancing nodeLocalLoadBalancing) {

            this.nodeLocalLoadBalancing = nodeLocalLoadBalancing;
            return this;
        }
        @CustomType.Setter
        public Builder podCIDR(@Nullable String podCIDR) {

            this.podCIDR = podCIDR;
            return this;
        }
        @CustomType.Setter
        public Builder provider(@Nullable String provider) {

            this.provider = provider;
            return this;
        }
        @CustomType.Setter
        public Builder serviceCIDR(@Nullable String serviceCIDR) {

            this.serviceCIDR = serviceCIDR;
            return this;
        }
        public K0sNetwork build() {
            final var _resultValue = new K0sNetwork();
            _resultValue.calico = calico;
            _resultValue.clusterDomain = clusterDomain;
            _resultValue.dualStack = dualStack;
            _resultValue.kubeProxy = kubeProxy;
            _resultValue.kuberouter = kuberouter;
            _resultValue.nodeLocalLoadBalancing = nodeLocalLoadBalancing;
            _resultValue.podCIDR = podCIDR;
            _resultValue.provider = provider;
            _resultValue.serviceCIDR = serviceCIDR;
            return _resultValue;
        }
    }
}
