// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class K0sWorkerProfile {
    private String name;
    private Map<String,String> values;

    private K0sWorkerProfile() {}
    public String name() {
        return this.name;
    }
    public Map<String,String> values() {
        return this.values;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(K0sWorkerProfile defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        private Map<String,String> values;
        public Builder() {}
        public Builder(K0sWorkerProfile defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.values = defaults.values;
        }

        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("K0sWorkerProfile", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder values(Map<String,String> values) {
            if (values == null) {
              throw new MissingRequiredPropertyException("K0sWorkerProfile", "values");
            }
            this.values = values;
            return this;
        }
        public K0sWorkerProfile build() {
            final var _resultValue = new K0sWorkerProfile();
            _resultValue.name = name;
            _resultValue.values = values;
            return _resultValue;
        }
    }
}
