// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterLocalhostArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterLocalhostArgs Empty = new ClusterLocalhostArgs();

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    private ClusterLocalhostArgs() {}

    private ClusterLocalhostArgs(ClusterLocalhostArgs $) {
        this.enabled = $.enabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterLocalhostArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterLocalhostArgs $;

        public Builder() {
            $ = new ClusterLocalhostArgs();
        }

        public Builder(ClusterLocalhostArgs defaults) {
            $ = new ClusterLocalhostArgs(Objects.requireNonNull(defaults));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public ClusterLocalhostArgs build() {
            return $;
        }
    }

}
