// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterOpenSSHArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterOpenSSHArgs Empty = new ClusterOpenSSHArgs();

    @Import(name="address", required=true)
    private Output<String> address;

    public Output<String> address() {
        return this.address;
    }

    @Import(name="configPath")
    private @Nullable Output<String> configPath;

    public Optional<Output<String>> configPath() {
        return Optional.ofNullable(this.configPath);
    }

    @Import(name="disableMultiplexing")
    private @Nullable Output<Boolean> disableMultiplexing;

    public Optional<Output<Boolean>> disableMultiplexing() {
        return Optional.ofNullable(this.disableMultiplexing);
    }

    @Import(name="key")
    private @Nullable Output<String> key;

    public Optional<Output<String>> key() {
        return Optional.ofNullable(this.key);
    }

    @Import(name="options")
    private @Nullable Output<Map<String,String>> options;

    public Optional<Output<Map<String,String>>> options() {
        return Optional.ofNullable(this.options);
    }

    @Import(name="port")
    private @Nullable Output<Integer> port;

    public Optional<Output<Integer>> port() {
        return Optional.ofNullable(this.port);
    }

    @Import(name="user")
    private @Nullable Output<String> user;

    public Optional<Output<String>> user() {
        return Optional.ofNullable(this.user);
    }

    private ClusterOpenSSHArgs() {}

    private ClusterOpenSSHArgs(ClusterOpenSSHArgs $) {
        this.address = $.address;
        this.configPath = $.configPath;
        this.disableMultiplexing = $.disableMultiplexing;
        this.key = $.key;
        this.options = $.options;
        this.port = $.port;
        this.user = $.user;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterOpenSSHArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterOpenSSHArgs $;

        public Builder() {
            $ = new ClusterOpenSSHArgs();
        }

        public Builder(ClusterOpenSSHArgs defaults) {
            $ = new ClusterOpenSSHArgs(Objects.requireNonNull(defaults));
        }

        public Builder address(Output<String> address) {
            $.address = address;
            return this;
        }

        public Builder address(String address) {
            return address(Output.of(address));
        }

        public Builder configPath(@Nullable Output<String> configPath) {
            $.configPath = configPath;
            return this;
        }

        public Builder configPath(String configPath) {
            return configPath(Output.of(configPath));
        }

        public Builder disableMultiplexing(@Nullable Output<Boolean> disableMultiplexing) {
            $.disableMultiplexing = disableMultiplexing;
            return this;
        }

        public Builder disableMultiplexing(Boolean disableMultiplexing) {
            return disableMultiplexing(Output.of(disableMultiplexing));
        }

        public Builder key(@Nullable Output<String> key) {
            $.key = key;
            return this;
        }

        public Builder key(String key) {
            return key(Output.of(key));
        }

        public Builder options(@Nullable Output<Map<String,String>> options) {
            $.options = options;
            return this;
        }

        public Builder options(Map<String,String> options) {
            return options(Output.of(options));
        }

        public Builder port(@Nullable Output<Integer> port) {
            $.port = port;
            return this;
        }

        public Builder port(Integer port) {
            return port(Output.of(port));
        }

        public Builder user(@Nullable Output<String> user) {
            $.user = user;
            return this;
        }

        public Builder user(String user) {
            return user(Output.of(user));
        }

        public ClusterOpenSSHArgs build() {
            if ($.address == null) {
                throw new MissingRequiredPropertyException("ClusterOpenSSHArgs", "address");
            }
            return $;
        }
    }

}
