// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterBastionArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterBastionArgs Empty = new ClusterBastionArgs();

    @Import(name="address", required=true)
    private Output<String> address;

    public Output<String> address() {
        return this.address;
    }

    @Import(name="hostKey")
    private @Nullable Output<String> hostKey;

    public Optional<Output<String>> hostKey() {
        return Optional.ofNullable(this.hostKey);
    }

    @Import(name="key")
    private @Nullable Output<String> key;

    public Optional<Output<String>> key() {
        return Optional.ofNullable(this.key);
    }

    @Import(name="port")
    private @Nullable Output<Integer> port;

    public Optional<Output<Integer>> port() {
        return Optional.ofNullable(this.port);
    }

    @Import(name="user")
    private @Nullable Output<String> user;

    public Optional<Output<String>> user() {
        return Optional.ofNullable(this.user);
    }

    private ClusterBastionArgs() {}

    private ClusterBastionArgs(ClusterBastionArgs $) {
        this.address = $.address;
        this.hostKey = $.hostKey;
        this.key = $.key;
        this.port = $.port;
        this.user = $.user;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterBastionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterBastionArgs $;

        public Builder() {
            $ = new ClusterBastionArgs();
        }

        public Builder(ClusterBastionArgs defaults) {
            $ = new ClusterBastionArgs(Objects.requireNonNull(defaults));
        }

        public Builder address(Output<String> address) {
            $.address = address;
            return this;
        }

        public Builder address(String address) {
            return address(Output.of(address));
        }

        public Builder hostKey(@Nullable Output<String> hostKey) {
            $.hostKey = hostKey;
            return this;
        }

        public Builder hostKey(String hostKey) {
            return hostKey(Output.of(hostKey));
        }

        public Builder key(@Nullable Output<String> key) {
            $.key = key;
            return this;
        }

        public Builder key(String key) {
            return key(Output.of(key));
        }

        public Builder port(@Nullable Output<Integer> port) {
            $.port = port;
            return this;
        }

        public Builder port(Integer port) {
            return port(Output.of(port));
        }

        public Builder user(@Nullable Output<String> user) {
            $.user = user;
            return this;
        }

        public Builder user(String user) {
            return user(Output.of(user));
        }

        public ClusterBastionArgs build() {
            if ($.address == null) {
                throw new MissingRequiredPropertyException("ClusterBastionArgs", "address");
            }
            return $;
        }
    }

}
