// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.ydkn.k0s.inputs.ClusterBastionArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterWinRMArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterWinRMArgs Empty = new ClusterWinRMArgs();

    @Import(name="address", required=true)
    private Output<String> address;

    public Output<String> address() {
        return this.address;
    }

    @Import(name="bastion")
    private @Nullable Output<ClusterBastionArgs> bastion;

    public Optional<Output<ClusterBastionArgs>> bastion() {
        return Optional.ofNullable(this.bastion);
    }

    @Import(name="caCert")
    private @Nullable Output<String> caCert;

    public Optional<Output<String>> caCert() {
        return Optional.ofNullable(this.caCert);
    }

    @Import(name="cert")
    private @Nullable Output<String> cert;

    public Optional<Output<String>> cert() {
        return Optional.ofNullable(this.cert);
    }

    @Import(name="insecure")
    private @Nullable Output<Boolean> insecure;

    public Optional<Output<Boolean>> insecure() {
        return Optional.ofNullable(this.insecure);
    }

    @Import(name="key")
    private @Nullable Output<String> key;

    public Optional<Output<String>> key() {
        return Optional.ofNullable(this.key);
    }

    @Import(name="password")
    private @Nullable Output<String> password;

    public Optional<Output<String>> password() {
        return Optional.ofNullable(this.password);
    }

    @Import(name="port")
    private @Nullable Output<Integer> port;

    public Optional<Output<Integer>> port() {
        return Optional.ofNullable(this.port);
    }

    @Import(name="tlsServerName")
    private @Nullable Output<String> tlsServerName;

    public Optional<Output<String>> tlsServerName() {
        return Optional.ofNullable(this.tlsServerName);
    }

    @Import(name="useHTTPS")
    private @Nullable Output<Boolean> useHTTPS;

    public Optional<Output<Boolean>> useHTTPS() {
        return Optional.ofNullable(this.useHTTPS);
    }

    @Import(name="useNTLM")
    private @Nullable Output<Boolean> useNTLM;

    public Optional<Output<Boolean>> useNTLM() {
        return Optional.ofNullable(this.useNTLM);
    }

    @Import(name="user")
    private @Nullable Output<String> user;

    public Optional<Output<String>> user() {
        return Optional.ofNullable(this.user);
    }

    private ClusterWinRMArgs() {}

    private ClusterWinRMArgs(ClusterWinRMArgs $) {
        this.address = $.address;
        this.bastion = $.bastion;
        this.caCert = $.caCert;
        this.cert = $.cert;
        this.insecure = $.insecure;
        this.key = $.key;
        this.password = $.password;
        this.port = $.port;
        this.tlsServerName = $.tlsServerName;
        this.useHTTPS = $.useHTTPS;
        this.useNTLM = $.useNTLM;
        this.user = $.user;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterWinRMArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterWinRMArgs $;

        public Builder() {
            $ = new ClusterWinRMArgs();
        }

        public Builder(ClusterWinRMArgs defaults) {
            $ = new ClusterWinRMArgs(Objects.requireNonNull(defaults));
        }

        public Builder address(Output<String> address) {
            $.address = address;
            return this;
        }

        public Builder address(String address) {
            return address(Output.of(address));
        }

        public Builder bastion(@Nullable Output<ClusterBastionArgs> bastion) {
            $.bastion = bastion;
            return this;
        }

        public Builder bastion(ClusterBastionArgs bastion) {
            return bastion(Output.of(bastion));
        }

        public Builder caCert(@Nullable Output<String> caCert) {
            $.caCert = caCert;
            return this;
        }

        public Builder caCert(String caCert) {
            return caCert(Output.of(caCert));
        }

        public Builder cert(@Nullable Output<String> cert) {
            $.cert = cert;
            return this;
        }

        public Builder cert(String cert) {
            return cert(Output.of(cert));
        }

        public Builder insecure(@Nullable Output<Boolean> insecure) {
            $.insecure = insecure;
            return this;
        }

        public Builder insecure(Boolean insecure) {
            return insecure(Output.of(insecure));
        }

        public Builder key(@Nullable Output<String> key) {
            $.key = key;
            return this;
        }

        public Builder key(String key) {
            return key(Output.of(key));
        }

        public Builder password(@Nullable Output<String> password) {
            $.password = password;
            return this;
        }

        public Builder password(String password) {
            return password(Output.of(password));
        }

        public Builder port(@Nullable Output<Integer> port) {
            $.port = port;
            return this;
        }

        public Builder port(Integer port) {
            return port(Output.of(port));
        }

        public Builder tlsServerName(@Nullable Output<String> tlsServerName) {
            $.tlsServerName = tlsServerName;
            return this;
        }

        public Builder tlsServerName(String tlsServerName) {
            return tlsServerName(Output.of(tlsServerName));
        }

        public Builder useHTTPS(@Nullable Output<Boolean> useHTTPS) {
            $.useHTTPS = useHTTPS;
            return this;
        }

        public Builder useHTTPS(Boolean useHTTPS) {
            return useHTTPS(Output.of(useHTTPS));
        }

        public Builder useNTLM(@Nullable Output<Boolean> useNTLM) {
            $.useNTLM = useNTLM;
            return this;
        }

        public Builder useNTLM(Boolean useNTLM) {
            return useNTLM(Output.of(useNTLM));
        }

        public Builder user(@Nullable Output<String> user) {
            $.user = user;
            return this;
        }

        public Builder user(String user) {
            return user(Output.of(user));
        }

        public ClusterWinRMArgs build() {
            if ($.address == null) {
                throw new MissingRequiredPropertyException("ClusterWinRMArgs", "address");
            }
            return $;
        }
    }

}
