// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterFileArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterFileArgs Empty = new ClusterFileArgs();

    @Import(name="dirPerm")
    private @Nullable Output<String> dirPerm;

    public Optional<Output<String>> dirPerm() {
        return Optional.ofNullable(this.dirPerm);
    }

    @Import(name="dst")
    private @Nullable Output<String> dst;

    public Optional<Output<String>> dst() {
        return Optional.ofNullable(this.dst);
    }

    @Import(name="dstDir")
    private @Nullable Output<String> dstDir;

    public Optional<Output<String>> dstDir() {
        return Optional.ofNullable(this.dstDir);
    }

    @Import(name="group")
    private @Nullable Output<String> group;

    public Optional<Output<String>> group() {
        return Optional.ofNullable(this.group);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="perm")
    private @Nullable Output<String> perm;

    public Optional<Output<String>> perm() {
        return Optional.ofNullable(this.perm);
    }

    @Import(name="src")
    private @Nullable Output<String> src;

    public Optional<Output<String>> src() {
        return Optional.ofNullable(this.src);
    }

    @Import(name="user")
    private @Nullable Output<String> user;

    public Optional<Output<String>> user() {
        return Optional.ofNullable(this.user);
    }

    private ClusterFileArgs() {}

    private ClusterFileArgs(ClusterFileArgs $) {
        this.dirPerm = $.dirPerm;
        this.dst = $.dst;
        this.dstDir = $.dstDir;
        this.group = $.group;
        this.name = $.name;
        this.perm = $.perm;
        this.src = $.src;
        this.user = $.user;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterFileArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterFileArgs $;

        public Builder() {
            $ = new ClusterFileArgs();
        }

        public Builder(ClusterFileArgs defaults) {
            $ = new ClusterFileArgs(Objects.requireNonNull(defaults));
        }

        public Builder dirPerm(@Nullable Output<String> dirPerm) {
            $.dirPerm = dirPerm;
            return this;
        }

        public Builder dirPerm(String dirPerm) {
            return dirPerm(Output.of(dirPerm));
        }

        public Builder dst(@Nullable Output<String> dst) {
            $.dst = dst;
            return this;
        }

        public Builder dst(String dst) {
            return dst(Output.of(dst));
        }

        public Builder dstDir(@Nullable Output<String> dstDir) {
            $.dstDir = dstDir;
            return this;
        }

        public Builder dstDir(String dstDir) {
            return dstDir(Output.of(dstDir));
        }

        public Builder group(@Nullable Output<String> group) {
            $.group = group;
            return this;
        }

        public Builder group(String group) {
            return group(Output.of(group));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder perm(@Nullable Output<String> perm) {
            $.perm = perm;
            return this;
        }

        public Builder perm(String perm) {
            return perm(Output.of(perm));
        }

        public Builder src(@Nullable Output<String> src) {
            $.src = src;
            return this;
        }

        public Builder src(String src) {
            return src(Output.of(src));
        }

        public Builder user(@Nullable Output<String> user) {
            $.user = user;
            return this;
        }

        public Builder user(String user) {
            return user(Output.of(user));
        }

        public ClusterFileArgs build() {
            return $;
        }
    }

}
