// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterHookArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterHookArgs Empty = new ClusterHookArgs();

    @Import(name="after")
    private @Nullable Output<List<String>> after;

    public Optional<Output<List<String>>> after() {
        return Optional.ofNullable(this.after);
    }

    @Import(name="before")
    private @Nullable Output<List<String>> before;

    public Optional<Output<List<String>>> before() {
        return Optional.ofNullable(this.before);
    }

    private ClusterHookArgs() {}

    private ClusterHookArgs(ClusterHookArgs $) {
        this.after = $.after;
        this.before = $.before;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterHookArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterHookArgs $;

        public Builder() {
            $ = new ClusterHookArgs();
        }

        public Builder(ClusterHookArgs defaults) {
            $ = new ClusterHookArgs(Objects.requireNonNull(defaults));
        }

        public Builder after(@Nullable Output<List<String>> after) {
            $.after = after;
            return this;
        }

        public Builder after(List<String> after) {
            return after(Output.of(after));
        }

        public Builder after(String... after) {
            return after(List.of(after));
        }

        public Builder before(@Nullable Output<List<String>> before) {
            $.before = before;
            return this;
        }

        public Builder before(List<String> before) {
            return before(Output.of(before));
        }

        public Builder before(String... before) {
            return before(List.of(before));
        }

        public ClusterHookArgs build() {
            return $;
        }
    }

}
