// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterMetadataArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterMetadataArgs Empty = new ClusterMetadataArgs();

    /**
     * The name of the cluster.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the cluster.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private ClusterMetadataArgs() {}

    private ClusterMetadataArgs(ClusterMetadataArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterMetadataArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterMetadataArgs $;

        public Builder() {
            $ = new ClusterMetadataArgs();
        }

        public Builder(ClusterMetadataArgs defaults) {
            $ = new ClusterMetadataArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the cluster.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the cluster.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public ClusterMetadataArgs build() {
            $.name = Codegen.stringProp("name").output().arg($.name).def("k0s").getNullable();
            return $;
        }
    }

}
