// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.ydkn.k0s.inputs.K0sImageArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class K0sCalicoImageArgs extends com.pulumi.resources.ResourceArgs {

    public static final K0sCalicoImageArgs Empty = new K0sCalicoImageArgs();

    @Import(name="cni")
    private @Nullable Output<K0sImageArgs> cni;

    public Optional<Output<K0sImageArgs>> cni() {
        return Optional.ofNullable(this.cni);
    }

    @Import(name="flexvolume")
    private @Nullable Output<K0sImageArgs> flexvolume;

    public Optional<Output<K0sImageArgs>> flexvolume() {
        return Optional.ofNullable(this.flexvolume);
    }

    @Import(name="kubecontrollers")
    private @Nullable Output<K0sImageArgs> kubecontrollers;

    public Optional<Output<K0sImageArgs>> kubecontrollers() {
        return Optional.ofNullable(this.kubecontrollers);
    }

    @Import(name="node")
    private @Nullable Output<K0sImageArgs> node;

    public Optional<Output<K0sImageArgs>> node() {
        return Optional.ofNullable(this.node);
    }

    private K0sCalicoImageArgs() {}

    private K0sCalicoImageArgs(K0sCalicoImageArgs $) {
        this.cni = $.cni;
        this.flexvolume = $.flexvolume;
        this.kubecontrollers = $.kubecontrollers;
        this.node = $.node;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(K0sCalicoImageArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private K0sCalicoImageArgs $;

        public Builder() {
            $ = new K0sCalicoImageArgs();
        }

        public Builder(K0sCalicoImageArgs defaults) {
            $ = new K0sCalicoImageArgs(Objects.requireNonNull(defaults));
        }

        public Builder cni(@Nullable Output<K0sImageArgs> cni) {
            $.cni = cni;
            return this;
        }

        public Builder cni(K0sImageArgs cni) {
            return cni(Output.of(cni));
        }

        public Builder flexvolume(@Nullable Output<K0sImageArgs> flexvolume) {
            $.flexvolume = flexvolume;
            return this;
        }

        public Builder flexvolume(K0sImageArgs flexvolume) {
            return flexvolume(Output.of(flexvolume));
        }

        public Builder kubecontrollers(@Nullable Output<K0sImageArgs> kubecontrollers) {
            $.kubecontrollers = kubecontrollers;
            return this;
        }

        public Builder kubecontrollers(K0sImageArgs kubecontrollers) {
            return kubecontrollers(Output.of(kubecontrollers));
        }

        public Builder node(@Nullable Output<K0sImageArgs> node) {
            $.node = node;
            return this;
        }

        public Builder node(K0sImageArgs node) {
            return node(Output.of(node));
        }

        public K0sCalicoImageArgs build() {
            return $;
        }
    }

}
