// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class K0sCalicoArgs extends com.pulumi.resources.ResourceArgs {

    public static final K0sCalicoArgs Empty = new K0sCalicoArgs();

    @Import(name="envVars")
    private @Nullable Output<Map<String,String>> envVars;

    public Optional<Output<Map<String,String>>> envVars() {
        return Optional.ofNullable(this.envVars);
    }

    @Import(name="flexVolumeDriverPath")
    private @Nullable Output<String> flexVolumeDriverPath;

    public Optional<Output<String>> flexVolumeDriverPath() {
        return Optional.ofNullable(this.flexVolumeDriverPath);
    }

    @Import(name="ipAutodetectionMethod")
    private @Nullable Output<String> ipAutodetectionMethod;

    public Optional<Output<String>> ipAutodetectionMethod() {
        return Optional.ofNullable(this.ipAutodetectionMethod);
    }

    @Import(name="mode")
    private @Nullable Output<String> mode;

    public Optional<Output<String>> mode() {
        return Optional.ofNullable(this.mode);
    }

    @Import(name="mtu")
    private @Nullable Output<Integer> mtu;

    public Optional<Output<Integer>> mtu() {
        return Optional.ofNullable(this.mtu);
    }

    @Import(name="overlay")
    private @Nullable Output<String> overlay;

    public Optional<Output<String>> overlay() {
        return Optional.ofNullable(this.overlay);
    }

    @Import(name="vxlanPort")
    private @Nullable Output<Integer> vxlanPort;

    public Optional<Output<Integer>> vxlanPort() {
        return Optional.ofNullable(this.vxlanPort);
    }

    @Import(name="vxlanVNI")
    private @Nullable Output<Integer> vxlanVNI;

    public Optional<Output<Integer>> vxlanVNI() {
        return Optional.ofNullable(this.vxlanVNI);
    }

    @Import(name="wireguard")
    private @Nullable Output<Boolean> wireguard;

    public Optional<Output<Boolean>> wireguard() {
        return Optional.ofNullable(this.wireguard);
    }

    private K0sCalicoArgs() {}

    private K0sCalicoArgs(K0sCalicoArgs $) {
        this.envVars = $.envVars;
        this.flexVolumeDriverPath = $.flexVolumeDriverPath;
        this.ipAutodetectionMethod = $.ipAutodetectionMethod;
        this.mode = $.mode;
        this.mtu = $.mtu;
        this.overlay = $.overlay;
        this.vxlanPort = $.vxlanPort;
        this.vxlanVNI = $.vxlanVNI;
        this.wireguard = $.wireguard;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(K0sCalicoArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private K0sCalicoArgs $;

        public Builder() {
            $ = new K0sCalicoArgs();
        }

        public Builder(K0sCalicoArgs defaults) {
            $ = new K0sCalicoArgs(Objects.requireNonNull(defaults));
        }

        public Builder envVars(@Nullable Output<Map<String,String>> envVars) {
            $.envVars = envVars;
            return this;
        }

        public Builder envVars(Map<String,String> envVars) {
            return envVars(Output.of(envVars));
        }

        public Builder flexVolumeDriverPath(@Nullable Output<String> flexVolumeDriverPath) {
            $.flexVolumeDriverPath = flexVolumeDriverPath;
            return this;
        }

        public Builder flexVolumeDriverPath(String flexVolumeDriverPath) {
            return flexVolumeDriverPath(Output.of(flexVolumeDriverPath));
        }

        public Builder ipAutodetectionMethod(@Nullable Output<String> ipAutodetectionMethod) {
            $.ipAutodetectionMethod = ipAutodetectionMethod;
            return this;
        }

        public Builder ipAutodetectionMethod(String ipAutodetectionMethod) {
            return ipAutodetectionMethod(Output.of(ipAutodetectionMethod));
        }

        public Builder mode(@Nullable Output<String> mode) {
            $.mode = mode;
            return this;
        }

        public Builder mode(String mode) {
            return mode(Output.of(mode));
        }

        public Builder mtu(@Nullable Output<Integer> mtu) {
            $.mtu = mtu;
            return this;
        }

        public Builder mtu(Integer mtu) {
            return mtu(Output.of(mtu));
        }

        public Builder overlay(@Nullable Output<String> overlay) {
            $.overlay = overlay;
            return this;
        }

        public Builder overlay(String overlay) {
            return overlay(Output.of(overlay));
        }

        public Builder vxlanPort(@Nullable Output<Integer> vxlanPort) {
            $.vxlanPort = vxlanPort;
            return this;
        }

        public Builder vxlanPort(Integer vxlanPort) {
            return vxlanPort(Output.of(vxlanPort));
        }

        public Builder vxlanVNI(@Nullable Output<Integer> vxlanVNI) {
            $.vxlanVNI = vxlanVNI;
            return this;
        }

        public Builder vxlanVNI(Integer vxlanVNI) {
            return vxlanVNI(Output.of(vxlanVNI));
        }

        public Builder wireguard(@Nullable Output<Boolean> wireguard) {
            $.wireguard = wireguard;
            return this;
        }

        public Builder wireguard(Boolean wireguard) {
            return wireguard(Output.of(wireguard));
        }

        public K0sCalicoArgs build() {
            return $;
        }
    }

}
