// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.ydkn.k0s.inputs.K0sEtcdExternalClusterArgs;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class K0sEtcdArgs extends com.pulumi.resources.ResourceArgs {

    public static final K0sEtcdArgs Empty = new K0sEtcdArgs();

    @Import(name="externalCluster")
    private @Nullable Output<K0sEtcdExternalClusterArgs> externalCluster;

    public Optional<Output<K0sEtcdExternalClusterArgs>> externalCluster() {
        return Optional.ofNullable(this.externalCluster);
    }

    @Import(name="extraArgs")
    private @Nullable Output<Map<String,String>> extraArgs;

    public Optional<Output<Map<String,String>>> extraArgs() {
        return Optional.ofNullable(this.extraArgs);
    }

    @Import(name="peerAddress")
    private @Nullable Output<String> peerAddress;

    public Optional<Output<String>> peerAddress() {
        return Optional.ofNullable(this.peerAddress);
    }

    private K0sEtcdArgs() {}

    private K0sEtcdArgs(K0sEtcdArgs $) {
        this.externalCluster = $.externalCluster;
        this.extraArgs = $.extraArgs;
        this.peerAddress = $.peerAddress;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(K0sEtcdArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private K0sEtcdArgs $;

        public Builder() {
            $ = new K0sEtcdArgs();
        }

        public Builder(K0sEtcdArgs defaults) {
            $ = new K0sEtcdArgs(Objects.requireNonNull(defaults));
        }

        public Builder externalCluster(@Nullable Output<K0sEtcdExternalClusterArgs> externalCluster) {
            $.externalCluster = externalCluster;
            return this;
        }

        public Builder externalCluster(K0sEtcdExternalClusterArgs externalCluster) {
            return externalCluster(Output.of(externalCluster));
        }

        public Builder extraArgs(@Nullable Output<Map<String,String>> extraArgs) {
            $.extraArgs = extraArgs;
            return this;
        }

        public Builder extraArgs(Map<String,String> extraArgs) {
            return extraArgs(Output.of(extraArgs));
        }

        public Builder peerAddress(@Nullable Output<String> peerAddress) {
            $.peerAddress = peerAddress;
            return this;
        }

        public Builder peerAddress(String peerAddress) {
            return peerAddress(Output.of(peerAddress));
        }

        public K0sEtcdArgs build() {
            return $;
        }
    }

}
