// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class K0sImageArgs extends com.pulumi.resources.ResourceArgs {

    public static final K0sImageArgs Empty = new K0sImageArgs();

    @Import(name="image")
    private @Nullable Output<String> image;

    public Optional<Output<String>> image() {
        return Optional.ofNullable(this.image);
    }

    @Import(name="version")
    private @Nullable Output<String> version;

    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    private K0sImageArgs() {}

    private K0sImageArgs(K0sImageArgs $) {
        this.image = $.image;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(K0sImageArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private K0sImageArgs $;

        public Builder() {
            $ = new K0sImageArgs();
        }

        public Builder(K0sImageArgs defaults) {
            $ = new K0sImageArgs(Objects.requireNonNull(defaults));
        }

        public Builder image(@Nullable Output<String> image) {
            $.image = image;
            return this;
        }

        public Builder image(String image) {
            return image(Output.of(image));
        }

        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        public Builder version(String version) {
            return version(Output.of(version));
        }

        public K0sImageArgs build() {
            return $;
        }
    }

}
