// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.ydkn.k0s.inputs.K0sKubeProxyIPTablesArgs;
import com.ydkn.k0s.inputs.K0sKubeProxyIPVSArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class K0sKubeProxyArgs extends com.pulumi.resources.ResourceArgs {

    public static final K0sKubeProxyArgs Empty = new K0sKubeProxyArgs();

    /**
     * Disable kube-proxy.
     * 
     */
    @Import(name="disabled")
    private @Nullable Output<Boolean> disabled;

    /**
     * @return Disable kube-proxy.
     * 
     */
    public Optional<Output<Boolean>> disabled() {
        return Optional.ofNullable(this.disabled);
    }

    @Import(name="iptables")
    private @Nullable Output<K0sKubeProxyIPTablesArgs> iptables;

    public Optional<Output<K0sKubeProxyIPTablesArgs>> iptables() {
        return Optional.ofNullable(this.iptables);
    }

    @Import(name="ipvs")
    private @Nullable Output<K0sKubeProxyIPVSArgs> ipvs;

    public Optional<Output<K0sKubeProxyIPVSArgs>> ipvs() {
        return Optional.ofNullable(this.ipvs);
    }

    /**
     * The kube-proxy mode to use. One of &#39;iptables&#39; or &#39;ipvs&#39;.
     * 
     */
    @Import(name="mode")
    private @Nullable Output<String> mode;

    /**
     * @return The kube-proxy mode to use. One of &#39;iptables&#39; or &#39;ipvs&#39;.
     * 
     */
    public Optional<Output<String>> mode() {
        return Optional.ofNullable(this.mode);
    }

    @Import(name="nodePortAddresses")
    private @Nullable Output<String> nodePortAddresses;

    public Optional<Output<String>> nodePortAddresses() {
        return Optional.ofNullable(this.nodePortAddresses);
    }

    private K0sKubeProxyArgs() {}

    private K0sKubeProxyArgs(K0sKubeProxyArgs $) {
        this.disabled = $.disabled;
        this.iptables = $.iptables;
        this.ipvs = $.ipvs;
        this.mode = $.mode;
        this.nodePortAddresses = $.nodePortAddresses;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(K0sKubeProxyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private K0sKubeProxyArgs $;

        public Builder() {
            $ = new K0sKubeProxyArgs();
        }

        public Builder(K0sKubeProxyArgs defaults) {
            $ = new K0sKubeProxyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param disabled Disable kube-proxy.
         * 
         * @return builder
         * 
         */
        public Builder disabled(@Nullable Output<Boolean> disabled) {
            $.disabled = disabled;
            return this;
        }

        /**
         * @param disabled Disable kube-proxy.
         * 
         * @return builder
         * 
         */
        public Builder disabled(Boolean disabled) {
            return disabled(Output.of(disabled));
        }

        public Builder iptables(@Nullable Output<K0sKubeProxyIPTablesArgs> iptables) {
            $.iptables = iptables;
            return this;
        }

        public Builder iptables(K0sKubeProxyIPTablesArgs iptables) {
            return iptables(Output.of(iptables));
        }

        public Builder ipvs(@Nullable Output<K0sKubeProxyIPVSArgs> ipvs) {
            $.ipvs = ipvs;
            return this;
        }

        public Builder ipvs(K0sKubeProxyIPVSArgs ipvs) {
            return ipvs(Output.of(ipvs));
        }

        /**
         * @param mode The kube-proxy mode to use. One of &#39;iptables&#39; or &#39;ipvs&#39;.
         * 
         * @return builder
         * 
         */
        public Builder mode(@Nullable Output<String> mode) {
            $.mode = mode;
            return this;
        }

        /**
         * @param mode The kube-proxy mode to use. One of &#39;iptables&#39; or &#39;ipvs&#39;.
         * 
         * @return builder
         * 
         */
        public Builder mode(String mode) {
            return mode(Output.of(mode));
        }

        public Builder nodePortAddresses(@Nullable Output<String> nodePortAddresses) {
            $.nodePortAddresses = nodePortAddresses;
            return this;
        }

        public Builder nodePortAddresses(String nodePortAddresses) {
            return nodePortAddresses(Output.of(nodePortAddresses));
        }

        public K0sKubeProxyArgs build() {
            $.disabled = Codegen.booleanProp("disabled").output().arg($.disabled).def(false).getNullable();
            $.mode = Codegen.stringProp("mode").output().arg($.mode).def("iptables").getNullable();
            return $;
        }
    }

}
