// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class K0sKubeProxyIPTablesArgs extends com.pulumi.resources.ResourceArgs {

    public static final K0sKubeProxyIPTablesArgs Empty = new K0sKubeProxyIPTablesArgs();

    @Import(name="masqueradeAll")
    private @Nullable Output<Boolean> masqueradeAll;

    public Optional<Output<Boolean>> masqueradeAll() {
        return Optional.ofNullable(this.masqueradeAll);
    }

    @Import(name="masqueradeBit")
    private @Nullable Output<Integer> masqueradeBit;

    public Optional<Output<Integer>> masqueradeBit() {
        return Optional.ofNullable(this.masqueradeBit);
    }

    @Import(name="minSyncPeriod")
    private @Nullable Output<String> minSyncPeriod;

    public Optional<Output<String>> minSyncPeriod() {
        return Optional.ofNullable(this.minSyncPeriod);
    }

    @Import(name="syncPeriod")
    private @Nullable Output<String> syncPeriod;

    public Optional<Output<String>> syncPeriod() {
        return Optional.ofNullable(this.syncPeriod);
    }

    private K0sKubeProxyIPTablesArgs() {}

    private K0sKubeProxyIPTablesArgs(K0sKubeProxyIPTablesArgs $) {
        this.masqueradeAll = $.masqueradeAll;
        this.masqueradeBit = $.masqueradeBit;
        this.minSyncPeriod = $.minSyncPeriod;
        this.syncPeriod = $.syncPeriod;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(K0sKubeProxyIPTablesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private K0sKubeProxyIPTablesArgs $;

        public Builder() {
            $ = new K0sKubeProxyIPTablesArgs();
        }

        public Builder(K0sKubeProxyIPTablesArgs defaults) {
            $ = new K0sKubeProxyIPTablesArgs(Objects.requireNonNull(defaults));
        }

        public Builder masqueradeAll(@Nullable Output<Boolean> masqueradeAll) {
            $.masqueradeAll = masqueradeAll;
            return this;
        }

        public Builder masqueradeAll(Boolean masqueradeAll) {
            return masqueradeAll(Output.of(masqueradeAll));
        }

        public Builder masqueradeBit(@Nullable Output<Integer> masqueradeBit) {
            $.masqueradeBit = masqueradeBit;
            return this;
        }

        public Builder masqueradeBit(Integer masqueradeBit) {
            return masqueradeBit(Output.of(masqueradeBit));
        }

        public Builder minSyncPeriod(@Nullable Output<String> minSyncPeriod) {
            $.minSyncPeriod = minSyncPeriod;
            return this;
        }

        public Builder minSyncPeriod(String minSyncPeriod) {
            return minSyncPeriod(Output.of(minSyncPeriod));
        }

        public Builder syncPeriod(@Nullable Output<String> syncPeriod) {
            $.syncPeriod = syncPeriod;
            return this;
        }

        public Builder syncPeriod(String syncPeriod) {
            return syncPeriod(Output.of(syncPeriod));
        }

        public K0sKubeProxyIPTablesArgs build() {
            return $;
        }
    }

}
