// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class K0sKubeProxyIPVSArgs extends com.pulumi.resources.ResourceArgs {

    public static final K0sKubeProxyIPVSArgs Empty = new K0sKubeProxyIPVSArgs();

    @Import(name="excludeCIDRs")
    private @Nullable Output<String> excludeCIDRs;

    public Optional<Output<String>> excludeCIDRs() {
        return Optional.ofNullable(this.excludeCIDRs);
    }

    @Import(name="minSyncPeriod")
    private @Nullable Output<String> minSyncPeriod;

    public Optional<Output<String>> minSyncPeriod() {
        return Optional.ofNullable(this.minSyncPeriod);
    }

    @Import(name="scheduler")
    private @Nullable Output<String> scheduler;

    public Optional<Output<String>> scheduler() {
        return Optional.ofNullable(this.scheduler);
    }

    @Import(name="strictARP")
    private @Nullable Output<Boolean> strictARP;

    public Optional<Output<Boolean>> strictARP() {
        return Optional.ofNullable(this.strictARP);
    }

    @Import(name="syncPeriod")
    private @Nullable Output<String> syncPeriod;

    public Optional<Output<String>> syncPeriod() {
        return Optional.ofNullable(this.syncPeriod);
    }

    @Import(name="tcpFinTimeout")
    private @Nullable Output<String> tcpFinTimeout;

    public Optional<Output<String>> tcpFinTimeout() {
        return Optional.ofNullable(this.tcpFinTimeout);
    }

    @Import(name="tcpTimeout")
    private @Nullable Output<String> tcpTimeout;

    public Optional<Output<String>> tcpTimeout() {
        return Optional.ofNullable(this.tcpTimeout);
    }

    @Import(name="udpTimeout")
    private @Nullable Output<String> udpTimeout;

    public Optional<Output<String>> udpTimeout() {
        return Optional.ofNullable(this.udpTimeout);
    }

    private K0sKubeProxyIPVSArgs() {}

    private K0sKubeProxyIPVSArgs(K0sKubeProxyIPVSArgs $) {
        this.excludeCIDRs = $.excludeCIDRs;
        this.minSyncPeriod = $.minSyncPeriod;
        this.scheduler = $.scheduler;
        this.strictARP = $.strictARP;
        this.syncPeriod = $.syncPeriod;
        this.tcpFinTimeout = $.tcpFinTimeout;
        this.tcpTimeout = $.tcpTimeout;
        this.udpTimeout = $.udpTimeout;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(K0sKubeProxyIPVSArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private K0sKubeProxyIPVSArgs $;

        public Builder() {
            $ = new K0sKubeProxyIPVSArgs();
        }

        public Builder(K0sKubeProxyIPVSArgs defaults) {
            $ = new K0sKubeProxyIPVSArgs(Objects.requireNonNull(defaults));
        }

        public Builder excludeCIDRs(@Nullable Output<String> excludeCIDRs) {
            $.excludeCIDRs = excludeCIDRs;
            return this;
        }

        public Builder excludeCIDRs(String excludeCIDRs) {
            return excludeCIDRs(Output.of(excludeCIDRs));
        }

        public Builder minSyncPeriod(@Nullable Output<String> minSyncPeriod) {
            $.minSyncPeriod = minSyncPeriod;
            return this;
        }

        public Builder minSyncPeriod(String minSyncPeriod) {
            return minSyncPeriod(Output.of(minSyncPeriod));
        }

        public Builder scheduler(@Nullable Output<String> scheduler) {
            $.scheduler = scheduler;
            return this;
        }

        public Builder scheduler(String scheduler) {
            return scheduler(Output.of(scheduler));
        }

        public Builder strictARP(@Nullable Output<Boolean> strictARP) {
            $.strictARP = strictARP;
            return this;
        }

        public Builder strictARP(Boolean strictARP) {
            return strictARP(Output.of(strictARP));
        }

        public Builder syncPeriod(@Nullable Output<String> syncPeriod) {
            $.syncPeriod = syncPeriod;
            return this;
        }

        public Builder syncPeriod(String syncPeriod) {
            return syncPeriod(Output.of(syncPeriod));
        }

        public Builder tcpFinTimeout(@Nullable Output<String> tcpFinTimeout) {
            $.tcpFinTimeout = tcpFinTimeout;
            return this;
        }

        public Builder tcpFinTimeout(String tcpFinTimeout) {
            return tcpFinTimeout(Output.of(tcpFinTimeout));
        }

        public Builder tcpTimeout(@Nullable Output<String> tcpTimeout) {
            $.tcpTimeout = tcpTimeout;
            return this;
        }

        public Builder tcpTimeout(String tcpTimeout) {
            return tcpTimeout(Output.of(tcpTimeout));
        }

        public Builder udpTimeout(@Nullable Output<String> udpTimeout) {
            $.udpTimeout = udpTimeout;
            return this;
        }

        public Builder udpTimeout(String udpTimeout) {
            return udpTimeout(Output.of(udpTimeout));
        }

        public K0sKubeProxyIPVSArgs build() {
            return $;
        }
    }

}
