// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class K0sMetadataArgs extends com.pulumi.resources.ResourceArgs {

    public static final K0sMetadataArgs Empty = new K0sMetadataArgs();

    /**
     * The name of the k0s cluster.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the k0s cluster.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private K0sMetadataArgs() {}

    private K0sMetadataArgs(K0sMetadataArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(K0sMetadataArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private K0sMetadataArgs $;

        public Builder() {
            $ = new K0sMetadataArgs();
        }

        public Builder(K0sMetadataArgs defaults) {
            $ = new K0sMetadataArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the k0s cluster.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the k0s cluster.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public K0sMetadataArgs build() {
            $.name = Codegen.stringProp("name").output().arg($.name).def("k0s").getNullable();
            return $;
        }
    }

}
