// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ydkn.k0s.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class K0sPodSecurityPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final K0sPodSecurityPolicyArgs Empty = new K0sPodSecurityPolicyArgs();

    /**
     * The default Pod Security Policy to use.
     * 
     */
    @Import(name="defaultPolicy")
    private @Nullable Output<String> defaultPolicy;

    /**
     * @return The default Pod Security Policy to use.
     * 
     */
    public Optional<Output<String>> defaultPolicy() {
        return Optional.ofNullable(this.defaultPolicy);
    }

    private K0sPodSecurityPolicyArgs() {}

    private K0sPodSecurityPolicyArgs(K0sPodSecurityPolicyArgs $) {
        this.defaultPolicy = $.defaultPolicy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(K0sPodSecurityPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private K0sPodSecurityPolicyArgs $;

        public Builder() {
            $ = new K0sPodSecurityPolicyArgs();
        }

        public Builder(K0sPodSecurityPolicyArgs defaults) {
            $ = new K0sPodSecurityPolicyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param defaultPolicy The default Pod Security Policy to use.
         * 
         * @return builder
         * 
         */
        public Builder defaultPolicy(@Nullable Output<String> defaultPolicy) {
            $.defaultPolicy = defaultPolicy;
            return this;
        }

        /**
         * @param defaultPolicy The default Pod Security Policy to use.
         * 
         * @return builder
         * 
         */
        public Builder defaultPolicy(String defaultPolicy) {
            return defaultPolicy(Output.of(defaultPolicy));
        }

        public K0sPodSecurityPolicyArgs build() {
            $.defaultPolicy = Codegen.stringProp("defaultPolicy").output().arg($.defaultPolicy).def("00-k0s-privileged").getNullable();
            return $;
        }
    }

}
