// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class Calico
    {
        public readonly string? FlexVolumeDriverPath;
        public readonly string? IpAutodetectionMethod;
        public readonly string? Mode;
        public readonly double? Mtu;
        public readonly string? Overlay;
        public readonly double? VxlanPort;
        public readonly double? VxlanVNI;
        public readonly bool? Wireguard;

        [OutputConstructor]
        private Calico(
            string? flexVolumeDriverPath,

            string? ipAutodetectionMethod,

            string? mode,

            double? mtu,

            string? overlay,

            double? vxlanPort,

            double? vxlanVNI,

            bool? wireguard)
        {
            FlexVolumeDriverPath = flexVolumeDriverPath;
            IpAutodetectionMethod = ipAutodetectionMethod;
            Mode = mode;
            Mtu = mtu;
            Overlay = overlay;
            VxlanPort = vxlanPort;
            VxlanVNI = vxlanVNI;
            Wireguard = wireguard;
        }
    }
}
