// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class ClusterWinRM
    {
        public readonly string Address;
        public readonly Outputs.ClusterSSH? Bastion;
        public readonly string? CaCert;
        public readonly string? Cert;
        public readonly bool? Insecure;
        public readonly string? Key;
        public readonly string? Password;
        public readonly int? Port;
        public readonly string? TlsServerName;
        public readonly bool? UseHTTPS;
        public readonly bool? UseNTLM;
        public readonly string? User;

        [OutputConstructor]
        private ClusterWinRM(
            string address,

            Outputs.ClusterSSH? bastion,

            string? caCert,

            string? cert,

            bool? insecure,

            string? key,

            string? password,

            int? port,

            string? tlsServerName,

            bool? useHTTPS,

            bool? useNTLM,

            string? user)
        {
            Address = address;
            Bastion = bastion;
            CaCert = caCert;
            Cert = cert;
            Insecure = insecure;
            Key = key;
            Password = password;
            Port = port;
            TlsServerName = tlsServerName;
            UseHTTPS = useHTTPS;
            UseNTLM = useNTLM;
            User = user;
        }
    }
}
