// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class ClusterInstallConfig
    {
        public readonly Outputs.ClusterInstallConfigUser? Users;

        [OutputConstructor]
        private ClusterInstallConfig(Outputs.ClusterInstallConfigUser? users)
        {
            Users = users;
        }
    }
}
