// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Outputs
{

    [OutputType]
    public sealed class ClusterK0s
    {
        /// <summary>
        /// K0s configuration.
        /// </summary>
        public readonly Outputs.K0s? Config;
        /// <summary>
        /// Whether to use dynamic configuration.
        /// </summary>
        public readonly bool? DynamicConfig;
        /// <summary>
        /// The hosts that will form the cluster.
        /// </summary>
        public readonly string? Version;
        /// <summary>
        /// The k0s version channel to use.
        /// </summary>
        public readonly string? VersionChannel;

        [OutputConstructor]
        private ClusterK0s(
            Outputs.K0s? config,

            bool? dynamicConfig,

            string? version,

            string? versionChannel)
        {
            Config = config;
            DynamicConfig = dynamicConfig;
            Version = version;
            VersionChannel = versionChannel;
        }
    }
}
