// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Outputs
{

    [OutputType]
    public sealed class ClusterOpenSSH
    {
        public readonly string Address;
        public readonly string? ConfigPath;
        public readonly bool? DisableMultiplexing;
        public readonly string? Key;
        public readonly ImmutableDictionary<string, string>? Options;
        public readonly int? Port;
        public readonly string? User;

        [OutputConstructor]
        private ClusterOpenSSH(
            string address,

            string? configPath,

            bool? disableMultiplexing,

            string? key,

            ImmutableDictionary<string, string>? options,

            int? port,

            string? user)
        {
            Address = address;
            ConfigPath = configPath;
            DisableMultiplexing = disableMultiplexing;
            Key = key;
            Options = options;
            Port = port;
            User = user;
        }
    }
}
