// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Outputs
{

    [OutputType]
    public sealed class ClusterSpec
    {
        /// <summary>
        /// The hosts that will form the cluster.
        /// </summary>
        public readonly ImmutableArray<Outputs.ClusterHost> Hosts;
        /// <summary>
        /// K0s configuration.
        /// </summary>
        public readonly Outputs.ClusterK0s? K0s;

        [OutputConstructor]
        private ClusterSpec(
            ImmutableArray<Outputs.ClusterHost> hosts,

            Outputs.ClusterK0s? k0s)
        {
            Hosts = hosts;
            K0s = k0s;
        }
    }
}
