// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Outputs
{

    [OutputType]
    public sealed class ClusterBastion
    {
        public readonly string Address;
        public readonly string? HostKey;
        public readonly string? Key;
        public readonly int? Port;
        public readonly string? User;

        [OutputConstructor]
        private ClusterBastion(
            string address,

            string? hostKey,

            string? key,

            int? port,

            string? user)
        {
            Address = address;
            HostKey = hostKey;
            Key = key;
            Port = port;
            User = user;
        }
    }
}
