// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class InstallConfigUsers
    {
        public readonly string? EtcdUser;
        public readonly string? KineUser;
        public readonly string? KonnectivityUser;
        public readonly string? KubeAPIserverUser;
        public readonly string? KubeSchedulerUser;

        [OutputConstructor]
        private InstallConfigUsers(
            string? etcdUser,

            string? kineUser,

            string? konnectivityUser,

            string? kubeAPIserverUser,

            string? kubeSchedulerUser)
        {
            EtcdUser = etcdUser;
            KineUser = kineUser;
            KonnectivityUser = konnectivityUser;
            KubeAPIserverUser = kubeAPIserverUser;
            KubeSchedulerUser = kubeSchedulerUser;
        }
    }
}
