// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Outputs
{

    [OutputType]
    public sealed class K0sAPI
    {
        public readonly string? Address;
        public readonly string? ExternalAddress;
        public readonly ImmutableDictionary<string, string>? ExtraArgs;
        /// <summary>
        /// The port the k0s API will listen on.
        /// </summary>
        public readonly int? K0sApiPort;
        /// <summary>
        /// The port the Kubernetes API will listen on.
        /// </summary>
        public readonly int? Port;
        public readonly ImmutableArray<string> Sans;

        [OutputConstructor]
        private K0sAPI(
            string? address,

            string? externalAddress,

            ImmutableDictionary<string, string>? extraArgs,

            int? k0sApiPort,

            int? port,

            ImmutableArray<string> sans)
        {
            Address = address;
            ExternalAddress = externalAddress;
            ExtraArgs = extraArgs;
            K0sApiPort = k0sApiPort;
            Port = port;
            Sans = sans;
        }
    }
}
