// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class K0sCalico
    {
        public readonly ImmutableDictionary<string, string>? EnvVars;
        public readonly string? FlexVolumeDriverPath;
        public readonly string? IpAutodetectionMethod;
        public readonly string? Mode;
        public readonly int? Mtu;
        public readonly string? Overlay;
        public readonly int? VxlanPort;
        public readonly int? VxlanVNI;
        public readonly bool? Wireguard;

        [OutputConstructor]
        private K0sCalico(
            ImmutableDictionary<string, string>? envVars,

            string? flexVolumeDriverPath,

            string? ipAutodetectionMethod,

            string? mode,

            int? mtu,

            string? overlay,

            int? vxlanPort,

            int? vxlanVNI,

            bool? wireguard)
        {
            EnvVars = envVars;
            FlexVolumeDriverPath = flexVolumeDriverPath;
            IpAutodetectionMethod = ipAutodetectionMethod;
            Mode = mode;
            Mtu = mtu;
            Overlay = overlay;
            VxlanPort = vxlanPort;
            VxlanVNI = vxlanVNI;
            Wireguard = wireguard;
        }
    }
}
