// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class K0sDualStack
    {
        public readonly string? IPv6podCIDR;
        public readonly string? IPv6serviceCIDR;
        public readonly bool? Enabled;

        [OutputConstructor]
        private K0sDualStack(
            string? IPv6podCIDR,

            string? IPv6serviceCIDR,

            bool? enabled)
        {
            this.IPv6podCIDR = IPv6podCIDR;
            this.IPv6serviceCIDR = IPv6serviceCIDR;
            Enabled = enabled;
        }
    }
}
