// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class K0sEtcdExternalCluster
    {
        public readonly string? Ca;
        public readonly string? ClientCert;
        public readonly string? ClientKey;
        public readonly ImmutableArray<string> Endpoints;
        public readonly string? EtcdPrefix;

        [OutputConstructor]
        private K0sEtcdExternalCluster(
            string? ca,

            string? clientCert,

            string? clientKey,

            ImmutableArray<string> endpoints,

            string? etcdPrefix)
        {
            Ca = ca;
            ClientCert = clientCert;
            ClientKey = clientKey;
            Endpoints = endpoints;
            EtcdPrefix = etcdPrefix;
        }
    }
}
