// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class K0sKubeRouterImage
    {
        public readonly Outputs.K0sImage? Cni;
        public readonly Outputs.K0sImage? CniInstaller;

        [OutputConstructor]
        private K0sKubeRouterImage(
            Outputs.K0sImage? cni,

            Outputs.K0sImage? cniInstaller)
        {
            Cni = cni;
            CniInstaller = cniInstaller;
        }
    }
}
