// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class K0sKonnectivity
    {
        public readonly int? AdminPort;
        public readonly int? AgentPort;

        [OutputConstructor]
        private K0sKonnectivity(
            int? adminPort,

            int? agentPort)
        {
            AdminPort = adminPort;
            AgentPort = agentPort;
        }
    }
}
