// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Outputs
{

    [OutputType]
    public sealed class K0sKubeRouter
    {
        /// <summary>
        /// Automatically detect and set the MTU based on the host interface.
        /// </summary>
        public readonly bool? AutoMTU;
        public readonly ImmutableDictionary<string, string>? ExtraArgs;
        public readonly string? Hairpin;
        public readonly bool? IpMasq;
        public readonly int? MetricsPort;
        /// <summary>
        /// The MTU to use for the kube-router network interfaces.
        /// </summary>
        public readonly int? Mtu;

        [OutputConstructor]
        private K0sKubeRouter(
            bool? autoMTU,

            ImmutableDictionary<string, string>? extraArgs,

            string? hairpin,

            bool? ipMasq,

            int? metricsPort,

            int? mtu)
        {
            AutoMTU = autoMTU;
            ExtraArgs = extraArgs;
            Hairpin = hairpin;
            IpMasq = ipMasq;
            MetricsPort = metricsPort;
            Mtu = mtu;
        }
    }
}
