// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Outputs
{

    [OutputType]
    public sealed class K0sKonnectivity
    {
        /// <summary>
        /// The port the konnectivity admin server will listen on.
        /// </summary>
        public readonly int? AdminPort;
        /// <summary>
        /// The port the konnectivity agent will listen on.
        /// </summary>
        public readonly int? AgentPort;

        [OutputConstructor]
        private K0sKonnectivity(
            int? adminPort,

            int? agentPort)
        {
            AdminPort = adminPort;
            AgentPort = agentPort;
        }
    }
}
