// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class K0sNodeLocalLoadBalancing
    {
        public readonly bool? Enabled;
        public readonly Outputs.K0sEnvoyProxy? EnvoyProxy;
        public readonly string? Type;

        [OutputConstructor]
        private K0sNodeLocalLoadBalancing(
            bool? enabled,

            Outputs.K0sEnvoyProxy? envoyProxy,

            string? type)
        {
            Enabled = enabled;
            EnvoyProxy = envoyProxy;
            Type = type;
        }
    }
}
