// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Outputs
{

    [OutputType]
    public sealed class K0sPodSecurityPolicy
    {
        /// <summary>
        /// The default Pod Security Policy to use.
        /// </summary>
        public readonly string? DefaultPolicy;

        [OutputConstructor]
        private K0sPodSecurityPolicy(string? defaultPolicy)
        {
            DefaultPolicy = defaultPolicy;
        }
    }
}
