// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class K0sSpec
    {
        public readonly Outputs.API? Api;
        public readonly Outputs.Images? Images;
        public readonly Outputs.InstallConfig? InstallConfig;
        public readonly Outputs.Konnectivity? Konnectivity;
        public readonly Outputs.Network? Network;
        public readonly Outputs.PodSecurityPolicy? PodSecurityPolicy;
        public readonly Outputs.Storage? Storage;
        public readonly Outputs.Telemetry? Telemetry;

        [OutputConstructor]
        private K0sSpec(
            Outputs.API? api,

            Outputs.Images? images,

            Outputs.InstallConfig? installConfig,

            Outputs.Konnectivity? konnectivity,

            Outputs.Network? network,

            Outputs.PodSecurityPolicy? podSecurityPolicy,

            Outputs.Storage? storage,

            Outputs.Telemetry? telemetry)
        {
            Api = api;
            Images = images;
            InstallConfig = installConfig;
            Konnectivity = konnectivity;
            Network = network;
            PodSecurityPolicy = podSecurityPolicy;
            Storage = storage;
            Telemetry = telemetry;
        }
    }
}
