// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Outputs
{

    [OutputType]
    public sealed class K0sWorkerProfile
    {
        public readonly string Name;
        public readonly ImmutableDictionary<string, string> Values;

        [OutputConstructor]
        private K0sWorkerProfile(
            string name,

            ImmutableDictionary<string, string> values)
        {
            Name = name;
            Values = values;
        }
    }
}
