// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class Network
    {
        public readonly Outputs.KubeProxy? KubeProxy;
        public readonly Outputs.KubeRouter? Kuberouter;
        public readonly string? PodCIDR;
        public readonly string? Provider;
        public readonly string? ServiceCIDR;

        [OutputConstructor]
        private Network(
            Outputs.KubeProxy? kubeProxy,

            Outputs.KubeRouter? kuberouter,

            string? podCIDR,

            string? provider,

            string? serviceCIDR)
        {
            KubeProxy = kubeProxy;
            Kuberouter = kuberouter;
            PodCIDR = podCIDR;
            Provider = provider;
            ServiceCIDR = serviceCIDR;
        }
    }
}
