// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Outputs
{

    [OutputType]
    public sealed class WinRM
    {
        public readonly string Address;
        public readonly Outputs.SSH? Bastion;
        public readonly string? CaCertPath;
        public readonly string? CertPath;
        public readonly bool? Insecure;
        public readonly string? KeyPath;
        public readonly string? Password;
        public readonly double? Port;
        public readonly string? TlsServerName;
        public readonly bool? UseHTTPS;
        public readonly bool? UseNTLM;
        public readonly string? User;

        [OutputConstructor]
        private WinRM(
            string address,

            Outputs.SSH? bastion,

            string? caCertPath,

            string? certPath,

            bool? insecure,

            string? keyPath,

            string? password,

            double? port,

            string? tlsServerName,

            bool? useHTTPS,

            bool? useNTLM,

            string? user)
        {
            Address = address;
            Bastion = bastion;
            CaCertPath = caCertPath;
            CertPath = certPath;
            Insecure = insecure;
            KeyPath = keyPath;
            Password = password;
            Port = port;
            TlsServerName = tlsServerName;
            UseHTTPS = useHTTPS;
            UseNTLM = useNTLM;
            User = user;
        }
    }
}
