// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ClusterFile {
    dirPerm?: string;
    dst?: string;
    dstDir?: string;
    group?: string;
    name?: string;
    perm?: string;
    src?: string;
    user?: string;
}

export interface ClusterHook {
    after?: string[];
    before?: string[];
}

export interface ClusterHooks {
    apply?: outputs.ClusterHook;
    backup?: outputs.ClusterHook;
    reset?: outputs.ClusterHook;
}

export interface ClusterHost {
    environment?: {[key: string]: string};
    files?: outputs.ClusterFile[];
    hooks?: outputs.ClusterHooks;
    hostname?: string;
    installFlags?: string[];
    k0sBinaryPath?: string;
    localhost?: outputs.ClusterLocalhost;
    noTaints?: boolean;
    os?: string;
    privateAddress?: string;
    privateInterface?: string;
    role: string;
    ssh?: outputs.ClusterSSH;
    uploadBinary?: boolean;
    winRM?: outputs.ClusterWinRM;
}

export interface ClusterK0s {
    config?: outputs.K0s;
    dynamicConfig?: boolean;
    version?: string;
    versionChannel?: string;
}

export interface ClusterLocalhost {
    enabled?: boolean;
}

export interface ClusterMetadata {
    name: string;
}

export interface ClusterSSH {
    address: string;
    bastion?: outputs.ClusterSSH;
    hostKey?: string;
    key?: string;
    port?: number;
    user?: string;
}

export interface ClusterSpec {
    hosts: outputs.ClusterHost[];
    k0s?: outputs.ClusterK0s;
}

export interface ClusterWinRM {
    address: string;
    bastion?: outputs.ClusterSSH;
    caCert?: string;
    cert?: string;
    insecure?: boolean;
    key?: string;
    password?: string;
    port?: number;
    tlsServerName?: string;
    useHTTPS?: boolean;
    useNTLM?: boolean;
    user?: string;
}

export interface K0s {
    apiVersion?: string;
    kind?: string;
    metadata?: outputs.K0sMetadata;
    spec?: outputs.K0sSpec;
}

export interface K0sAPI {
    address?: string;
    externalAddress?: string;
    extraArgs?: {[key: string]: string};
    k0sApiPort?: number;
    port?: number;
    sans?: string[];
}

export interface K0sCalico {
    envVars?: {[key: string]: string};
    flexVolumeDriverPath?: string;
    ipAutodetectionMethod?: string;
    mode?: string;
    mtu?: number;
    overlay?: string;
    vxlanPort?: number;
    vxlanVNI?: number;
    wireguard?: boolean;
}

export interface K0sCalicoImage {
    cni?: outputs.K0sImage;
    flexvolume?: outputs.K0sImage;
    kubecontrollers?: outputs.K0sImage;
    node?: outputs.K0sImage;
}

export interface K0sControllerManager {
    extraArgs?: {[key: string]: string};
}

export interface K0sDualStack {
    IPv6podCIDR?: string;
    IPv6serviceCIDR?: string;
    enabled?: boolean;
}

export interface K0sEnvoyProxy {
    apiServerBindPort?: number;
    image?: string;
    imagePullPolicy?: string;
    konnectivityServerBindPort?: number;
}

export interface K0sEtcd {
    externalCluster?: outputs.K0sEtcdExternalCluster;
    extraArgs?: {[key: string]: string};
    peerAddress?: string;
}

export interface K0sEtcdExternalCluster {
    ca?: string;
    clientCert?: string;
    clientKey?: string;
    endpoints: string[];
    etcdPrefix?: string;
}

export interface K0sFeatureGate {
    components?: string[];
    enabled?: boolean;
    name: string;
}

export interface K0sImage {
    image?: string;
    version?: string;
}

export interface K0sImages {
    calico?: outputs.K0sCalicoImage;
    coredns?: outputs.K0sImage;
    default_pull_policy?: string;
    konnectivity?: outputs.K0sImage;
    kubeproxy?: outputs.K0sImage;
    kuberouter?: outputs.K0sKubeRouterImage;
    metricsserver?: outputs.K0sImage;
    pause?: outputs.K0sImage;
    repository?: string;
}

export interface K0sInstallConfig {
    users?: outputs.K0sInstallConfigUser;
}

export interface K0sInstallConfigUser {
    etcdUser?: string;
    kineUser?: string;
    konnectivityUser?: string;
    kubeAPIserverUser?: string;
    kubeSchedulerUser?: string;
}

export interface K0sKine {
    dataSource: string;
}

export interface K0sKonnectivity {
    adminPort?: number;
    agentPort?: number;
}

export interface K0sKubeProxy {
    disabled?: boolean;
    iptables?: outputs.K0sKubeProxyIPTables;
    ipvs?: outputs.K0sKubeProxyIPVS;
    mode?: string;
    nodePortAddresses?: string;
}

export interface K0sKubeProxyIPTables {
    masqueradeAll?: boolean;
    masqueradeBit?: number;
    minSyncPeriod?: string;
    syncPeriod?: string;
}

export interface K0sKubeProxyIPVS {
    excludeCIDRs?: string;
    minSyncPeriod?: string;
    scheduler?: string;
    strictARP?: boolean;
    syncPeriod?: string;
    tcpFinTimeout?: string;
    tcpTimeout?: string;
    udpTimeout?: string;
}

export interface K0sKubeRouter {
    autoMTU?: boolean;
    extraArgs?: {[key: string]: string};
    hairpin?: string;
    ipMasq?: boolean;
    metricsPort?: number;
    mtu?: number;
}

export interface K0sKubeRouterImage {
    cni?: outputs.K0sImage;
    cniInstaller?: outputs.K0sImage;
}

export interface K0sMetadata {
    name: string;
}

export interface K0sNetwork {
    calico?: outputs.K0sCalico;
    clusterDomain?: string;
    dualStack?: outputs.K0sDualStack;
    kubeProxy?: outputs.K0sKubeProxy;
    kuberouter?: outputs.K0sKubeRouter;
    nodeLocalLoadBalancing?: outputs.K0sNodeLocalLoadBalancing;
    podCIDR?: string;
    provider?: string;
    serviceCIDR?: string;
}

export interface K0sNodeLocalLoadBalancing {
    enabled?: boolean;
    envoyProxy?: outputs.K0sEnvoyProxy;
    type?: string;
}

export interface K0sPodSecurityPolicy {
    defaultPolicy?: string;
}

export interface K0sScheduler {
    extraArgs?: {[key: string]: string};
}

export interface K0sSpec {
    api?: outputs.K0sAPI;
    controllerManager?: outputs.K0sControllerManager;
    featureGates?: outputs.K0sFeatureGate[];
    images?: outputs.K0sImages;
    installConfig?: outputs.K0sInstallConfig;
    konnectivity?: outputs.K0sKonnectivity;
    network?: outputs.K0sNetwork;
    podSecurityPolicy?: outputs.K0sPodSecurityPolicy;
    scheduler?: outputs.K0sScheduler;
    storage?: outputs.K0sStorage;
    telemetry?: outputs.K0sTelemetry;
    workerProfiles?: outputs.K0sWorkerProfile[];
}

export interface K0sStorage {
    etcd?: outputs.K0sEtcd;
    kine?: outputs.K0sKine;
    type?: string;
}

export interface K0sTelemetry {
    enabled?: boolean;
}

export interface K0sWorkerProfile {
    name: string;
    values: {[key: string]: any};
}

