// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class CalicoArgs : global::Pulumi.ResourceArgs
    {
        [Input("flexVolumeDriverPath")]
        public Input<string>? FlexVolumeDriverPath { get; set; }

        [Input("ipAutodetectionMethod")]
        public Input<string>? IpAutodetectionMethod { get; set; }

        [Input("mode")]
        public Input<string>? Mode { get; set; }

        [Input("mtu")]
        public Input<double>? Mtu { get; set; }

        [Input("overlay")]
        public Input<string>? Overlay { get; set; }

        [Input("vxlanPort")]
        public Input<double>? VxlanPort { get; set; }

        [Input("vxlanVNI")]
        public Input<double>? VxlanVNI { get; set; }

        [Input("wireguard")]
        public Input<bool>? Wireguard { get; set; }

        public CalicoArgs()
        {
        }
        public static new CalicoArgs Empty => new CalicoArgs();
    }
}
