// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class ClusterNodeLocalLoadBalancingArgs : global::Pulumi.ResourceArgs
    {
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("envoyProxy")]
        public Input<Inputs.ClusterEnvoyProxyArgs>? EnvoyProxy { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public ClusterNodeLocalLoadBalancingArgs()
        {
        }
        public static new ClusterNodeLocalLoadBalancingArgs Empty => new ClusterNodeLocalLoadBalancingArgs();
    }
}
