// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Inputs
{

    public sealed class ClusterSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("hosts", required: true)]
        private InputList<Inputs.ClusterHostArgs>? _hosts;

        /// <summary>
        /// The hosts that will form the cluster.
        /// </summary>
        public InputList<Inputs.ClusterHostArgs> Hosts
        {
            get => _hosts ?? (_hosts = new InputList<Inputs.ClusterHostArgs>());
            set => _hosts = value;
        }

        /// <summary>
        /// K0s configuration.
        /// </summary>
        [Input("k0s")]
        public Input<Inputs.ClusterK0sArgs>? K0s { get; set; }

        public ClusterSpecArgs()
        {
        }
        public static new ClusterSpecArgs Empty => new ClusterSpecArgs();
    }
}
