// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class ClusterInstallConfigUserArgs : global::Pulumi.ResourceArgs
    {
        [Input("etcdUser")]
        public Input<string>? EtcdUser { get; set; }

        [Input("kineUser")]
        public Input<string>? KineUser { get; set; }

        [Input("konnectivityUser")]
        public Input<string>? KonnectivityUser { get; set; }

        [Input("kubeAPIserverUser")]
        public Input<string>? KubeAPIserverUser { get; set; }

        [Input("kubeSchedulerUser")]
        public Input<string>? KubeSchedulerUser { get; set; }

        public ClusterInstallConfigUserArgs()
        {
        }
        public static new ClusterInstallConfigUserArgs Empty => new ClusterInstallConfigUserArgs();
    }
}
