// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Inputs
{

    public sealed class K0sAPIArgs : global::Pulumi.ResourceArgs
    {
        [Input("address")]
        public Input<string>? Address { get; set; }

        [Input("externalAddress")]
        public Input<string>? ExternalAddress { get; set; }

        [Input("extraArgs")]
        private InputMap<string>? _extraArgs;
        public InputMap<string> ExtraArgs
        {
            get => _extraArgs ?? (_extraArgs = new InputMap<string>());
            set => _extraArgs = value;
        }

        /// <summary>
        /// The port the k0s API will listen on.
        /// </summary>
        [Input("k0sApiPort")]
        public Input<int>? K0sApiPort { get; set; }

        /// <summary>
        /// The port the Kubernetes API will listen on.
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("sans")]
        private InputList<string>? _sans;
        public InputList<string> Sans
        {
            get => _sans ?? (_sans = new InputList<string>());
            set => _sans = value;
        }

        public K0sAPIArgs()
        {
            K0sApiPort = 9443;
            Port = 6443;
        }
        public static new K0sAPIArgs Empty => new K0sAPIArgs();
    }
}
