// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class K0sInstallConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("users")]
        public Input<Inputs.K0sInstallConfigUserArgs>? Users { get; set; }

        public K0sInstallConfigArgs()
        {
        }
        public static new K0sInstallConfigArgs Empty => new K0sInstallConfigArgs();
    }
}
