// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class K0sImagesArgs : global::Pulumi.ResourceArgs
    {
        [Input("calico")]
        public Input<Inputs.K0sCalicoImageArgs>? Calico { get; set; }

        [Input("coredns")]
        public Input<Inputs.K0sImageArgs>? Coredns { get; set; }

        [Input("default_pull_policy")]
        public Input<string>? Default_pull_policy { get; set; }

        [Input("konnectivity")]
        public Input<Inputs.K0sImageArgs>? Konnectivity { get; set; }

        [Input("kubeproxy")]
        public Input<Inputs.K0sImageArgs>? Kubeproxy { get; set; }

        [Input("kuberouter")]
        public Input<Inputs.K0sKubeRouterImageArgs>? Kuberouter { get; set; }

        [Input("metricsserver")]
        public Input<Inputs.K0sImageArgs>? Metricsserver { get; set; }

        [Input("pause")]
        public Input<Inputs.K0sImageArgs>? Pause { get; set; }

        [Input("repository")]
        public Input<string>? Repository { get; set; }

        public K0sImagesArgs()
        {
        }
        public static new K0sImagesArgs Empty => new K0sImagesArgs();
    }
}
