// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class K0sKineArgs : global::Pulumi.ResourceArgs
    {
        [Input("dataSource", required: true)]
        private Input<string>? _dataSource;
        public Input<string>? DataSource
        {
            get => _dataSource;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _dataSource = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public K0sKineArgs()
        {
        }
        public static new K0sKineArgs Empty => new K0sKineArgs();
    }
}
