// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Inputs
{

    public sealed class K0sKonnectivityArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The port the konnectivity admin server will listen on.
        /// </summary>
        [Input("adminPort")]
        public Input<int>? AdminPort { get; set; }

        /// <summary>
        /// The port the konnectivity agent will listen on.
        /// </summary>
        [Input("agentPort")]
        public Input<int>? AgentPort { get; set; }

        public K0sKonnectivityArgs()
        {
            AdminPort = 8133;
            AgentPort = 8132;
        }
        public static new K0sKonnectivityArgs Empty => new K0sKonnectivityArgs();
    }
}
