// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class K0sPodSecurityPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("defaultPolicy")]
        public Input<string>? DefaultPolicy { get; set; }

        public K0sPodSecurityPolicyArgs()
        {
        }
        public static new K0sPodSecurityPolicyArgs Empty => new K0sPodSecurityPolicyArgs();
    }
}
