// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Inputs
{

    public sealed class K0sSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// K0s API configuration.
        /// </summary>
        [Input("api")]
        public Input<Inputs.K0sAPIArgs>? Api { get; set; }

        /// <summary>
        /// K0s controller manager configuration.
        /// </summary>
        [Input("controllerManager")]
        public Input<Inputs.K0sControllerManagerArgs>? ControllerManager { get; set; }

        [Input("featureGates")]
        private InputList<Inputs.K0sFeatureGateArgs>? _featureGates;

        /// <summary>
        /// K0s feature gates configuration.
        /// </summary>
        public InputList<Inputs.K0sFeatureGateArgs> FeatureGates
        {
            get => _featureGates ?? (_featureGates = new InputList<Inputs.K0sFeatureGateArgs>());
            set => _featureGates = value;
        }

        /// <summary>
        /// K0s images configuration.
        /// </summary>
        [Input("images")]
        public Input<Inputs.K0sImagesArgs>? Images { get; set; }

        /// <summary>
        /// K0s install configuration.
        /// </summary>
        [Input("installConfig")]
        public Input<Inputs.K0sInstallConfigArgs>? InstallConfig { get; set; }

        /// <summary>
        /// K0s konnectivity configuration.
        /// </summary>
        [Input("konnectivity")]
        public Input<Inputs.K0sKonnectivityArgs>? Konnectivity { get; set; }

        /// <summary>
        /// K0s network configuration.
        /// </summary>
        [Input("network")]
        public Input<Inputs.K0sNetworkArgs>? Network { get; set; }

        /// <summary>
        /// K0s pod security policy configuration.
        /// </summary>
        [Input("podSecurityPolicy")]
        public Input<Inputs.K0sPodSecurityPolicyArgs>? PodSecurityPolicy { get; set; }

        /// <summary>
        /// K0s scheduler configuration.
        /// </summary>
        [Input("scheduler")]
        public Input<Inputs.K0sSchedulerArgs>? Scheduler { get; set; }

        /// <summary>
        /// K0s storage configuration.
        /// </summary>
        [Input("storage")]
        public Input<Inputs.K0sStorageArgs>? Storage { get; set; }

        /// <summary>
        /// K0s telemetry configuration.
        /// </summary>
        [Input("telemetry")]
        public Input<Inputs.K0sTelemetryArgs>? Telemetry { get; set; }

        [Input("workerProfiles")]
        private InputList<Inputs.K0sWorkerProfileArgs>? _workerProfiles;

        /// <summary>
        /// K0s worker profiles configuration.
        /// </summary>
        public InputList<Inputs.K0sWorkerProfileArgs> WorkerProfiles
        {
            get => _workerProfiles ?? (_workerProfiles = new InputList<Inputs.K0sWorkerProfileArgs>());
            set => _workerProfiles = value;
        }

        public K0sSpecArgs()
        {
        }
        public static new K0sSpecArgs Empty => new K0sSpecArgs();
    }
}
