// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Inputs
{

    public sealed class K0sStorageArgs : global::Pulumi.ResourceArgs
    {
        [Input("etcd")]
        public Input<Inputs.K0sEtcdArgs>? Etcd { get; set; }

        [Input("kine")]
        public Input<Inputs.K0sKineArgs>? Kine { get; set; }

        /// <summary>
        /// The storage type to use. One of 'etcd' or 'kine'.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public K0sStorageArgs()
        {
            Type = "etcd";
        }
        public static new K0sStorageArgs Empty => new K0sStorageArgs();
    }
}
