// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class K0sStorageArgs : global::Pulumi.ResourceArgs
    {
        [Input("etcd")]
        public Input<Inputs.K0sEtcdArgs>? Etcd { get; set; }

        [Input("kine")]
        public Input<Inputs.K0sKineArgs>? Kine { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public K0sStorageArgs()
        {
        }
        public static new K0sStorageArgs Empty => new K0sStorageArgs();
    }
}
