// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ydkn.K0s.Inputs
{

    public sealed class K0sTelemetryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable or disable telemetry.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        public K0sTelemetryArgs()
        {
            Enabled = true;
        }
        public static new K0sTelemetryArgs Empty => new K0sTelemetryArgs();
    }
}
