// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class KineArgs : global::Pulumi.ResourceArgs
    {
        [Input("dataSource", required: true)]
        public Input<string> DataSource { get; set; } = null!;

        public KineArgs()
        {
        }
        public static new KineArgs Empty => new KineArgs();
    }
}
