// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class NetworkArgs : global::Pulumi.ResourceArgs
    {
        [Input("calico")]
        public Input<Inputs.CalicoArgs>? Calico { get; set; }

        [Input("dualStack")]
        public Input<Inputs.DualStackArgs>? DualStack { get; set; }

        [Input("kubeProxy")]
        public Input<Inputs.KubeProxyArgs>? KubeProxy { get; set; }

        [Input("kuberouter")]
        public Input<Inputs.KubeRouterArgs>? Kuberouter { get; set; }

        [Input("podCIDR")]
        public Input<string>? PodCIDR { get; set; }

        [Input("provider")]
        public Input<string>? Provider { get; set; }

        [Input("serviceCIDR")]
        public Input<string>? ServiceCIDR { get; set; }

        public NetworkArgs()
        {
        }
        public static new NetworkArgs Empty => new NetworkArgs();
    }
}
