// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class PodSecurityPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("defaultPolicy")]
        public Input<string>? DefaultPolicy { get; set; }

        public PodSecurityPolicyArgs()
        {
        }
        public static new PodSecurityPolicyArgs Empty => new PodSecurityPolicyArgs();
    }
}
