// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class StorageArgs : global::Pulumi.ResourceArgs
    {
        [Input("etcd")]
        public Input<Inputs.EtcdArgs>? Etcd { get; set; }

        [Input("kine")]
        public Input<Inputs.KineArgs>? Kine { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public StorageArgs()
        {
        }
        public static new StorageArgs Empty => new StorageArgs();
    }
}
