// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.K0s.Inputs
{

    public sealed class WinRMArgs : global::Pulumi.ResourceArgs
    {
        [Input("address", required: true)]
        public Input<string> Address { get; set; } = null!;

        [Input("bastion")]
        public Input<Inputs.SSHArgs>? Bastion { get; set; }

        [Input("caCertPath")]
        public Input<string>? CaCertPath { get; set; }

        [Input("certPath")]
        public Input<string>? CertPath { get; set; }

        [Input("insecure")]
        public Input<bool>? Insecure { get; set; }

        [Input("keyPath")]
        public Input<string>? KeyPath { get; set; }

        [Input("password")]
        public Input<string>? Password { get; set; }

        [Input("port")]
        public Input<double>? Port { get; set; }

        [Input("tlsServerName")]
        public Input<string>? TlsServerName { get; set; }

        [Input("useHTTPS")]
        public Input<bool>? UseHTTPS { get; set; }

        [Input("useNTLM")]
        public Input<bool>? UseNTLM { get; set; }

        [Input("user")]
        public Input<string>? User { get; set; }

        public WinRMArgs()
        {
        }
        public static new WinRMArgs Empty => new WinRMArgs();
    }
}
