name: Makefile

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/pulumi/devcontainer:base
      options: --user root
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        id: git
        with:
          submodules: "recursive"
      - name: Unshallow clone for tags
        id: tags
        run: |
          sudo chown -R $(whoami) /__w/pulumi-k0s/pulumi-k0s
          git config --global --add safe.directory /__w/pulumi-k0s/pulumi-k0s
          git fetch --prune --unshallow --tags
      - name: Build
        id: build
        run: |
          make build
      - name: Install
        id: install
        run: |
          set -ex
          make install
      # - name: PulumiUp
      #   id: up
      #   run: |
      #     make up
      # - name: PulumiDown
      #   id: down
      #   run: |
      #     make down
      - name: Generate multi-language examples from yaml IaC program
        id: examples
        run: |
          set -ex
          make gen_examples
