name: release

on:
  push:
    tags:
      - "v*"

env:
  # THIS GITHUB_TOKEN IS A REQUIREMENT TO BE ABLE TO WRITE TO GH RELEASES
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  # SDK versions
  NODEJS_VERSION: 22
  PYTHON_VERSION: 3.x
  DOTNET_VERSION: 8.0.x

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: ${{env.NODEJS_VERSION}}
          registry-url: https://registry.npmjs.org

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Set up .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Install Pulumi CLI
        uses: pulumi/actions@v6

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: pulumi/pulumictl

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload archives
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.S3_REGION }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 cp dist/ "s3://${S3_BUCKET}/pulumi-k0s/" \
            --endpoint-url "${S3_ENDPOINT}" \
            --recursive \
            --exclude "*" \
            --include "*.tar.gz"

      - name: Build Node.js SDK
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: make nodejs_sdk PROVIDER_VERSION=${GITHUB_REF_NAME}

      - name: Build Python SDK
        run: make python_sdk PROVIDER_VERSION=${GITHUB_REF_NAME}

      - name: Build .NET SDK
        run: make dotnet_sdk PROVIDER_VERSION=${GITHUB_REF_NAME}

      - name: Publish Node.js SDK to npm
        working-directory: sdk/nodejs/bin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish --access public

      - name: Publish Python SDK to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_AUTH_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_AUTH_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          python -m twine upload sdk/python/bin/dist/*

      - name: Publish .NET SDK to NuGet
        run: |
          dotnet nuget push sdk/dotnet/bin/Debug/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_PUBLISH_KEY }} \
            --skip-duplicate
