// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The k0s cluster resource.
 */
export class Cluster extends pulumi.CustomResource {
    /**
     * Get an existing Cluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Cluster {
        return new Cluster(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'k0s:index:Cluster';

    /**
     * Returns true if the given object is an instance of Cluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Cluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Cluster.__pulumiType;
    }

    /**
     * The API version of the cluster resource.
     */
    declare public readonly apiVersion: pulumi.Output<string | undefined>;
    /**
     * The kind of the cluster resource.
     */
    declare public readonly kind: pulumi.Output<string | undefined>;
    /**
     * The kubeconfig file content to access the created k0s cluster.
     */
    declare public /*out*/ readonly kubeconfig: pulumi.Output<string>;
    /**
     * Metadata of the cluster resource.
     */
    declare public readonly metadata: pulumi.Output<outputs.ClusterMetadata | undefined>;
    /**
     * Specification of the cluster resource.
     */
    declare public readonly spec: pulumi.Output<outputs.ClusterSpec | undefined>;

    /**
     * Create a Cluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ClusterArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = (args?.apiVersion) ?? "k0sctl.k0sproject.io/v1beta1";
            resourceInputs["kind"] = (args?.kind) ?? "Cluster";
            resourceInputs["metadata"] = args ? pulumi.output(args.metadata).apply(v => v === undefined ? undefined : inputs.clusterMetadataArgsProvideDefaults(v)) : undefined;
            resourceInputs["spec"] = args ? pulumi.output(args.spec).apply(v => v === undefined ? undefined : inputs.clusterSpecArgsProvideDefaults(v)) : undefined;
            resourceInputs["kubeconfig"] = undefined /*out*/;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["kubeconfig"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["kubeconfig"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Cluster.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Cluster resource.
 */
export interface ClusterArgs {
    /**
     * The API version of the cluster resource.
     */
    apiVersion?: pulumi.Input<string | undefined>;
    /**
     * The kind of the cluster resource.
     */
    kind?: pulumi.Input<string | undefined>;
    /**
     * Metadata of the cluster resource.
     */
    metadata?: pulumi.Input<inputs.ClusterMetadataArgs | undefined>;
    /**
     * Specification of the cluster resource.
     */
    spec?: pulumi.Input<inputs.ClusterSpecArgs | undefined>;
}
