# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

noDrain: bool
"""
Do not drain nodes before upgrades/updates.
"""

skipDowngradeCheck: bool
"""
Do not check if a downgrade would be performed.
"""

