# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('k0s')


class _ExportableConfig(types.ModuleType):
    @property
    def no_drain(self) -> bool:
        """
        Do not drain nodes before upgrades/updates.
        """
        return __config__.get_bool('noDrain') or (_utilities.get_env_bool('PULUMI_K0S_NO_DRAIN') or False)

    @property
    def skip_downgrade_check(self) -> bool:
        """
        Do not check if a downgrade would be performed.
        """
        return __config__.get_bool('skipDowngradeCheck') or (_utilities.get_env_bool('PULUMI_K0S_SKIP_DOWNGRADE_CHECK') or False)

